<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible chapters/verses including
    An English book name (as a comment only)
        (This table should be language agnostic although English is used as a meta-language.)
    A three character reference code (upper case, no spaces, begin with a letter, matches BibleBooksCodes.xml)
    The number of chapters in the book
    The number of verses in each chapter of the book
All books (including Deutero-canonical/Apocryphal and combined books) should be included even if normally unused.

The data is preceded by a header of the same format as an OSIS header.

Note that the data is supplied as XML elements, not attributes.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleVersificationSystem [
    <!ELEMENT BibleVersificationSystem (header,BibleBookVersification+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|cre|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleBookVersification (nameEnglish,referenceAbbreviation,numChapters,numVerses+)>
            <!ELEMENT nameEnglish (#PCDATA)>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT numChapters (#PCDATA)>
            <!ELEMENT numVerses (#PCDATA)>
                <!ATTLIST numVerses
                    chapter CDATA #REQUIRED
                    omittedVerses CDATA #IMPLIED
                    combinedVerses CDATA #IMPLIED
                    reorderedVerses CDATA #IMPLIED>
]>

<BibleVersificationSystem>

  <header>
    <work>
      <version>0.22</version>
      <date>2013-01-17</date>
      <title>Latin Vulgate Bible versification system</title>
      <contributor role="com">Robert Hunt</contributor>
      <rights>Public Domain</rights>
    </work>
  </header>

  <BibleBookVersification>
    <nameEnglish>Genesis</nameEnglish>
    <referenceAbbreviation>GEN</referenceAbbreviation>
    <numChapters>50</numChapters>
    <numVerses chapter="1">31</numVerses>
    <numVerses chapter="2">25</numVerses>
    <numVerses chapter="3">24</numVerses>
    <numVerses chapter="4">26</numVerses>
    <numVerses chapter="5">32</numVerses>
    <numVerses chapter="6">22</numVerses>
    <numVerses chapter="7">24</numVerses>
    <numVerses chapter="8">22</numVerses>
    <numVerses chapter="9">29</numVerses>
    <numVerses chapter="10">32</numVerses>
    <numVerses chapter="11">32</numVerses>
    <numVerses chapter="12">20</numVerses>
    <numVerses chapter="13">18</numVerses>
    <numVerses chapter="14">24</numVerses>
    <numVerses chapter="15">21</numVerses>
    <numVerses chapter="16">16</numVerses>
    <numVerses chapter="17">27</numVerses>
    <numVerses chapter="18">33</numVerses>
    <numVerses chapter="19">38</numVerses>
    <numVerses chapter="20">18</numVerses>
    <numVerses chapter="21">34</numVerses>
    <numVerses chapter="22">24</numVerses>
    <numVerses chapter="23">20</numVerses>
    <numVerses chapter="24">67</numVerses>
    <numVerses chapter="25">34</numVerses>
    <numVerses chapter="26">35</numVerses>
    <numVerses chapter="27">46</numVerses>
    <numVerses chapter="28">22</numVerses>
    <numVerses chapter="29">35</numVerses>
    <numVerses chapter="30">43</numVerses>
    <numVerses chapter="31">55</numVerses>
    <numVerses chapter="32">32</numVerses>
    <numVerses chapter="33">20</numVerses>
    <numVerses chapter="34">31</numVerses>
    <numVerses chapter="35">29</numVerses>
    <numVerses chapter="36">43</numVerses>
    <numVerses chapter="37">36</numVerses>
    <numVerses chapter="38">30</numVerses>
    <numVerses chapter="39">23</numVerses>
    <numVerses chapter="40">23</numVerses>
    <numVerses chapter="41">57</numVerses>
    <numVerses chapter="42">38</numVerses>
    <numVerses chapter="43">34</numVerses>
    <numVerses chapter="44">34</numVerses>
    <numVerses chapter="45">28</numVerses>
    <numVerses chapter="46">34</numVerses>
    <numVerses chapter="47">31</numVerses>
    <numVerses chapter="48">22</numVerses>
    <numVerses chapter="49">32</numVerses>
    <numVerses chapter="50">25</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Exodus</nameEnglish>
    <referenceAbbreviation>EXO</referenceAbbreviation>
    <numChapters>40</numChapters>
    <numVerses chapter="1">22</numVerses>
    <numVerses chapter="2">25</numVerses>
    <numVerses chapter="3">22</numVerses>
    <numVerses chapter="4">31</numVerses>
    <numVerses chapter="5">23</numVerses>
    <numVerses chapter="6">30</numVerses>
    <numVerses chapter="7">25</numVerses>
    <numVerses chapter="8">32</numVerses>
    <numVerses chapter="9">35</numVerses>
    <numVerses chapter="10">29</numVerses>
    <numVerses chapter="11">10</numVerses>
    <numVerses chapter="12">51</numVerses>
    <numVerses chapter="13">22</numVerses>
    <numVerses chapter="14">31</numVerses>
    <numVerses chapter="15">27</numVerses>
    <numVerses chapter="16">36</numVerses>
    <numVerses chapter="17">16</numVerses>
    <numVerses chapter="18">27</numVerses>
    <numVerses chapter="19">25</numVerses>
    <numVerses chapter="20">26</numVerses>
    <numVerses chapter="21">36</numVerses>
    <numVerses chapter="22">31</numVerses>
    <numVerses chapter="23">33</numVerses>
    <numVerses chapter="24">18</numVerses>
    <numVerses chapter="25">40</numVerses>
    <numVerses chapter="26">37</numVerses>
    <numVerses chapter="27">21</numVerses>
    <numVerses chapter="28">43</numVerses>
    <numVerses chapter="29">46</numVerses>
    <numVerses chapter="30">38</numVerses>
    <numVerses chapter="31">18</numVerses>
    <numVerses chapter="32">35</numVerses>
    <numVerses chapter="33">23</numVerses>
    <numVerses chapter="34">35</numVerses>
    <numVerses chapter="35">35</numVerses>
    <numVerses chapter="36">38</numVerses>
    <numVerses chapter="37">29</numVerses>
    <numVerses chapter="38">31</numVerses>
    <numVerses chapter="39">43</numVerses>
    <numVerses chapter="40">36</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Leviticus</nameEnglish>
    <referenceAbbreviation>LEV</referenceAbbreviation>
    <numChapters>27</numChapters>
    <numVerses chapter="1">17</numVerses>
    <numVerses chapter="2">16</numVerses>
    <numVerses chapter="3">17</numVerses>
    <numVerses chapter="4">35</numVerses>
    <numVerses chapter="5">19</numVerses>
    <numVerses chapter="6">30</numVerses>
    <numVerses chapter="7">38</numVerses>
    <numVerses chapter="8">36</numVerses>
    <numVerses chapter="9">24</numVerses>
    <numVerses chapter="10">20</numVerses>
    <numVerses chapter="11">47</numVerses>
    <numVerses chapter="12">8</numVerses>
    <numVerses chapter="13">59</numVerses>
    <numVerses chapter="14">57</numVerses>
    <numVerses chapter="15">33</numVerses>
    <numVerses chapter="16">34</numVerses>
    <numVerses chapter="17">16</numVerses>
    <numVerses chapter="18">30</numVerses>
    <numVerses chapter="19">37</numVerses>
    <numVerses chapter="20">27</numVerses>
    <numVerses chapter="21">24</numVerses>
    <numVerses chapter="22">33</numVerses>
    <numVerses chapter="23">44</numVerses>
    <numVerses chapter="24">23</numVerses>
    <numVerses chapter="25">55</numVerses>
    <numVerses chapter="26">45</numVerses>
    <numVerses chapter="27">34</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Numbers</nameEnglish>
    <referenceAbbreviation>NUM</referenceAbbreviation>
    <numChapters>36</numChapters>
    <numVerses chapter="1">54</numVerses>
    <numVerses chapter="2">34</numVerses>
    <numVerses chapter="3">51</numVerses>
    <numVerses chapter="4">49</numVerses>
    <numVerses chapter="5">31</numVerses>
    <numVerses chapter="6">27</numVerses>
    <numVerses chapter="7">89</numVerses>
    <numVerses chapter="8">26</numVerses>
    <numVerses chapter="9">23</numVerses>
    <numVerses chapter="10">36</numVerses>
    <numVerses chapter="11">34</numVerses>
    <numVerses chapter="12">15</numVerses>
    <numVerses chapter="13">34</numVerses>
    <numVerses chapter="14">45</numVerses>
    <numVerses chapter="15">41</numVerses>
    <numVerses chapter="16">50</numVerses>
    <numVerses chapter="17">13</numVerses>
    <numVerses chapter="18">32</numVerses>
    <numVerses chapter="19">22</numVerses>
    <numVerses chapter="20">30</numVerses>
    <numVerses chapter="21">35</numVerses>
    <numVerses chapter="22">41</numVerses>
    <numVerses chapter="23">30</numVerses>
    <numVerses chapter="24">25</numVerses>
    <numVerses chapter="25">18</numVerses>
    <numVerses chapter="26">65</numVerses>
    <numVerses chapter="27">23</numVerses>
    <numVerses chapter="28">31</numVerses>
    <numVerses chapter="29">39</numVerses>
    <numVerses chapter="30">17</numVerses>
    <numVerses chapter="31">54</numVerses>
    <numVerses chapter="32">42</numVerses>
    <numVerses chapter="33">56</numVerses>
    <numVerses chapter="34">29</numVerses>
    <numVerses chapter="35">34</numVerses>
    <numVerses chapter="36">13</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Deuteronomy</nameEnglish>
    <referenceAbbreviation>DEU</referenceAbbreviation>
    <numChapters>34</numChapters>
    <numVerses chapter="1">46</numVerses>
    <numVerses chapter="2">37</numVerses>
    <numVerses chapter="3">29</numVerses>
    <numVerses chapter="4">49</numVerses>
    <numVerses chapter="5">33</numVerses>
    <numVerses chapter="6">25</numVerses>
    <numVerses chapter="7">26</numVerses>
    <numVerses chapter="8">20</numVerses>
    <numVerses chapter="9">29</numVerses>
    <numVerses chapter="10">22</numVerses>
    <numVerses chapter="11">32</numVerses>
    <numVerses chapter="12">32</numVerses>
    <numVerses chapter="13">18</numVerses>
    <numVerses chapter="14">29</numVerses>
    <numVerses chapter="15">23</numVerses>
    <numVerses chapter="16">22</numVerses>
    <numVerses chapter="17">20</numVerses>
    <numVerses chapter="18">22</numVerses>
    <numVerses chapter="19">21</numVerses>
    <numVerses chapter="20">20</numVerses>
    <numVerses chapter="21">23</numVerses>
    <numVerses chapter="22">30</numVerses>
    <numVerses chapter="23">25</numVerses>
    <numVerses chapter="24">22</numVerses>
    <numVerses chapter="25">19</numVerses>
    <numVerses chapter="26">19</numVerses>
    <numVerses chapter="27">26</numVerses>
    <numVerses chapter="28">68</numVerses>
    <numVerses chapter="29">29</numVerses>
    <numVerses chapter="30">20</numVerses>
    <numVerses chapter="31">30</numVerses>
    <numVerses chapter="32">52</numVerses>
    <numVerses chapter="33">29</numVerses>
    <numVerses chapter="34">12</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Joshua</nameEnglish>
    <referenceAbbreviation>JOS</referenceAbbreviation>
    <numChapters>24</numChapters>
    <numVerses chapter="1">18</numVerses>
    <numVerses chapter="2">24</numVerses>
    <numVerses chapter="3">17</numVerses>
    <numVerses chapter="4">25</numVerses>
    <numVerses chapter="5">16</numVerses>
    <numVerses chapter="6">27</numVerses>
    <numVerses chapter="7">26</numVerses>
    <numVerses chapter="8">35</numVerses>
    <numVerses chapter="9">27</numVerses>
    <numVerses chapter="10">43</numVerses>
    <numVerses chapter="11">23</numVerses>
    <numVerses chapter="12">24</numVerses>
    <numVerses chapter="13">33</numVerses>
    <numVerses chapter="14">15</numVerses>
    <numVerses chapter="15">63</numVerses>
    <numVerses chapter="16">10</numVerses>
    <numVerses chapter="17">18</numVerses>
    <numVerses chapter="18">28</numVerses>
    <numVerses chapter="19">51</numVerses>
    <numVerses chapter="20">9</numVerses>
    <numVerses chapter="21">43</numVerses>
    <numVerses chapter="22">34</numVerses>
    <numVerses chapter="23">16</numVerses>
    <numVerses chapter="24">33</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Judges</nameEnglish>
    <referenceAbbreviation>JDG</referenceAbbreviation>
    <numChapters>21</numChapters>
    <numVerses chapter="1">36</numVerses>
    <numVerses chapter="2">23</numVerses>
    <numVerses chapter="3">31</numVerses>
    <numVerses chapter="4">24</numVerses>
    <numVerses chapter="5">32</numVerses>
    <numVerses chapter="6">40</numVerses>
    <numVerses chapter="7">25</numVerses>
    <numVerses chapter="8">35</numVerses>
    <numVerses chapter="9">57</numVerses>
    <numVerses chapter="10">18</numVerses>
    <numVerses chapter="11">40</numVerses>
    <numVerses chapter="12">15</numVerses>
    <numVerses chapter="13">25</numVerses>
    <numVerses chapter="14">20</numVerses>
    <numVerses chapter="15">20</numVerses>
    <numVerses chapter="16">31</numVerses>
    <numVerses chapter="17">13</numVerses>
    <numVerses chapter="18">31</numVerses>
    <numVerses chapter="19">30</numVerses>
    <numVerses chapter="20">48</numVerses>
    <numVerses chapter="21">24</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Ruth</nameEnglish>
    <referenceAbbreviation>RUT</referenceAbbreviation>
    <numChapters>4</numChapters>
    <numVerses chapter="1">22</numVerses>
    <numVerses chapter="2">23</numVerses>
    <numVerses chapter="3">18</numVerses>
    <numVerses chapter="4">22</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>1 Samuel</nameEnglish>
    <referenceAbbreviation>SA1</referenceAbbreviation>
    <numChapters>31</numChapters>
    <numVerses chapter="1">28</numVerses>
    <numVerses chapter="2">36</numVerses>
    <numVerses chapter="3">21</numVerses>
    <numVerses chapter="4">22</numVerses>
    <numVerses chapter="5">12</numVerses>
    <numVerses chapter="6">21</numVerses>
    <numVerses chapter="7">17</numVerses>
    <numVerses chapter="8">22</numVerses>
    <numVerses chapter="9">27</numVerses>
    <numVerses chapter="10">27</numVerses>
    <numVerses chapter="11">15</numVerses>
    <numVerses chapter="12">25</numVerses>
    <numVerses chapter="13">23</numVerses>
    <numVerses chapter="14">52</numVerses>
    <numVerses chapter="15">35</numVerses>
    <numVerses chapter="16">23</numVerses>
    <numVerses chapter="17">58</numVerses>
    <numVerses chapter="18">30</numVerses>
    <numVerses chapter="19">24</numVerses>
    <numVerses chapter="20">43</numVerses>
    <numVerses chapter="21">15</numVerses>
    <numVerses chapter="22">23</numVerses>
    <numVerses chapter="23">28</numVerses>
    <numVerses chapter="24">23</numVerses>
    <numVerses chapter="25">44</numVerses>
    <numVerses chapter="26">25</numVerses>
    <numVerses chapter="27">12</numVerses>
    <numVerses chapter="28">25</numVerses>
    <numVerses chapter="29">11</numVerses>
    <numVerses chapter="30">31</numVerses>
    <numVerses chapter="31">13</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>2 Samuel</nameEnglish>
    <referenceAbbreviation>SA2</referenceAbbreviation>
    <numChapters>24</numChapters>
    <numVerses chapter="1">27</numVerses>
    <numVerses chapter="2">32</numVerses>
    <numVerses chapter="3">39</numVerses>
    <numVerses chapter="4">12</numVerses>
    <numVerses chapter="5">25</numVerses>
    <numVerses chapter="6">23</numVerses>
    <numVerses chapter="7">29</numVerses>
    <numVerses chapter="8">18</numVerses>
    <numVerses chapter="9">13</numVerses>
    <numVerses chapter="10">19</numVerses>
    <numVerses chapter="11">27</numVerses>
    <numVerses chapter="12">31</numVerses>
    <numVerses chapter="13">39</numVerses>
    <numVerses chapter="14">33</numVerses>
    <numVerses chapter="15">37</numVerses>
    <numVerses chapter="16">23</numVerses>
    <numVerses chapter="17">29</numVerses>
    <numVerses chapter="18">33</numVerses>
    <numVerses chapter="19">43</numVerses>
    <numVerses chapter="20">26</numVerses>
    <numVerses chapter="21">22</numVerses>
    <numVerses chapter="22">51</numVerses>
    <numVerses chapter="23">39</numVerses>
    <numVerses chapter="24">25</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>1 Kings</nameEnglish>
    <referenceAbbreviation>KI1</referenceAbbreviation>
    <numChapters>22</numChapters>
    <numVerses chapter="1">53</numVerses>
    <numVerses chapter="2">46</numVerses>
    <numVerses chapter="3">28</numVerses>
    <numVerses chapter="4">34</numVerses>
    <numVerses chapter="5">18</numVerses>
    <numVerses chapter="6">38</numVerses>
    <numVerses chapter="7">51</numVerses>
    <numVerses chapter="8">66</numVerses>
    <numVerses chapter="9">28</numVerses>
    <numVerses chapter="10">29</numVerses>
    <numVerses chapter="11">43</numVerses>
    <numVerses chapter="12">33</numVerses>
    <numVerses chapter="13">34</numVerses>
    <numVerses chapter="14">31</numVerses>
    <numVerses chapter="15">34</numVerses>
    <numVerses chapter="16">34</numVerses>
    <numVerses chapter="17">24</numVerses>
    <numVerses chapter="18">46</numVerses>
    <numVerses chapter="19">21</numVerses>
    <numVerses chapter="20">43</numVerses>
    <numVerses chapter="21">29</numVerses>
    <numVerses chapter="22">54</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>2 Kings</nameEnglish>
    <referenceAbbreviation>KI2</referenceAbbreviation>
    <numChapters>25</numChapters>
    <numVerses chapter="1">18</numVerses>
    <numVerses chapter="2">25</numVerses>
    <numVerses chapter="3">27</numVerses>
    <numVerses chapter="4">44</numVerses>
    <numVerses chapter="5">27</numVerses>
    <numVerses chapter="6">33</numVerses>
    <numVerses chapter="7">20</numVerses>
    <numVerses chapter="8">29</numVerses>
    <numVerses chapter="9">37</numVerses>
    <numVerses chapter="10">36</numVerses>
    <numVerses chapter="11">21</numVerses>
    <numVerses chapter="12">21</numVerses>
    <numVerses chapter="13">25</numVerses>
    <numVerses chapter="14">29</numVerses>
    <numVerses chapter="15">38</numVerses>
    <numVerses chapter="16">20</numVerses>
    <numVerses chapter="17">41</numVerses>
    <numVerses chapter="18">37</numVerses>
    <numVerses chapter="19">37</numVerses>
    <numVerses chapter="20">21</numVerses>
    <numVerses chapter="21">26</numVerses>
    <numVerses chapter="22">20</numVerses>
    <numVerses chapter="23">37</numVerses>
    <numVerses chapter="24">20</numVerses>
    <numVerses chapter="25">30</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>1 Chronicles</nameEnglish>
    <referenceAbbreviation>CH1</referenceAbbreviation>
    <numChapters>29</numChapters>
    <numVerses chapter="1">54</numVerses>
    <numVerses chapter="2">55</numVerses>
    <numVerses chapter="3">24</numVerses>
    <numVerses chapter="4">43</numVerses>
    <numVerses chapter="5">26</numVerses>
    <numVerses chapter="6">81</numVerses>
    <numVerses chapter="7">40</numVerses>
    <numVerses chapter="8">40</numVerses>
    <numVerses chapter="9">44</numVerses>
    <numVerses chapter="10">14</numVerses>
    <numVerses chapter="11">46</numVerses>
    <numVerses chapter="12">40</numVerses>
    <numVerses chapter="13">14</numVerses>
    <numVerses chapter="14">17</numVerses>
    <numVerses chapter="15">29</numVerses>
    <numVerses chapter="16">43</numVerses>
    <numVerses chapter="17">27</numVerses>
    <numVerses chapter="18">17</numVerses>
    <numVerses chapter="19">19</numVerses>
    <numVerses chapter="20">7</numVerses>
    <numVerses chapter="21">30</numVerses>
    <numVerses chapter="22">19</numVerses>
    <numVerses chapter="23">32</numVerses>
    <numVerses chapter="24">31</numVerses>
    <numVerses chapter="25">31</numVerses>
    <numVerses chapter="26">32</numVerses>
    <numVerses chapter="27">34</numVerses>
    <numVerses chapter="28">21</numVerses>
    <numVerses chapter="29">30</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>2 Chronicles</nameEnglish>
    <referenceAbbreviation>CH2</referenceAbbreviation>
    <numChapters>36</numChapters>
    <numVerses chapter="1">17</numVerses>
    <numVerses chapter="2">18</numVerses>
    <numVerses chapter="3">17</numVerses>
    <numVerses chapter="4">22</numVerses>
    <numVerses chapter="5">14</numVerses>
    <numVerses chapter="6">42</numVerses>
    <numVerses chapter="7">22</numVerses>
    <numVerses chapter="8">18</numVerses>
    <numVerses chapter="9">31</numVerses>
    <numVerses chapter="10">19</numVerses>
    <numVerses chapter="11">23</numVerses>
    <numVerses chapter="12">16</numVerses>
    <numVerses chapter="13">22</numVerses>
    <numVerses chapter="14">15</numVerses>
    <numVerses chapter="15">19</numVerses>
    <numVerses chapter="16">14</numVerses>
    <numVerses chapter="17">19</numVerses>
    <numVerses chapter="18">34</numVerses>
    <numVerses chapter="19">11</numVerses>
    <numVerses chapter="20">37</numVerses>
    <numVerses chapter="21">20</numVerses>
    <numVerses chapter="22">12</numVerses>
    <numVerses chapter="23">21</numVerses>
    <numVerses chapter="24">27</numVerses>
    <numVerses chapter="25">28</numVerses>
    <numVerses chapter="26">23</numVerses>
    <numVerses chapter="27">9</numVerses>
    <numVerses chapter="28">27</numVerses>
    <numVerses chapter="29">36</numVerses>
    <numVerses chapter="30">27</numVerses>
    <numVerses chapter="31">21</numVerses>
    <numVerses chapter="32">33</numVerses>
    <numVerses chapter="33">25</numVerses>
    <numVerses chapter="34">33</numVerses>
    <numVerses chapter="35">27</numVerses>
    <numVerses chapter="36">23</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Ezra</nameEnglish>
    <referenceAbbreviation>EZR</referenceAbbreviation>
    <numChapters>10</numChapters>
    <numVerses chapter="1">11</numVerses>
    <numVerses chapter="2">70</numVerses>
    <numVerses chapter="3">13</numVerses>
    <numVerses chapter="4">24</numVerses>
    <numVerses chapter="5">17</numVerses>
    <numVerses chapter="6">22</numVerses>
    <numVerses chapter="7">28</numVerses>
    <numVerses chapter="8">36</numVerses>
    <numVerses chapter="9">15</numVerses>
    <numVerses chapter="10">44</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Nehemiah</nameEnglish>
    <referenceAbbreviation>NEH</referenceAbbreviation>
    <numChapters>13</numChapters>
    <numVerses chapter="1">11</numVerses>
    <numVerses chapter="2">20</numVerses>
    <numVerses chapter="3">31</numVerses>
    <numVerses chapter="4">23</numVerses>
    <numVerses chapter="5">19</numVerses>
    <numVerses chapter="6">19</numVerses>
    <numVerses chapter="7">73</numVerses>
    <numVerses chapter="8">18</numVerses>
    <numVerses chapter="9">38</numVerses>
    <numVerses chapter="10">39</numVerses>
    <numVerses chapter="11">36</numVerses>
    <numVerses chapter="12">46</numVerses>
    <numVerses chapter="13">31</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Esther</nameEnglish>
    <referenceAbbreviation>EST</referenceAbbreviation>
    <numChapters>16</numChapters>
    <numVerses chapter="1">22</numVerses>
    <numVerses chapter="2">23</numVerses>
    <numVerses chapter="3">15</numVerses>
    <numVerses chapter="4">17</numVerses>
    <numVerses chapter="5">14</numVerses>
    <numVerses chapter="6">14</numVerses>
    <numVerses chapter="7">10</numVerses>
    <numVerses chapter="8">17</numVerses>
    <numVerses chapter="9">32</numVerses>
    <numVerses chapter="10">13</numVerses>
    <numVerses chapter="11">12</numVerses>
    <numVerses chapter="12">6</numVerses>
    <numVerses chapter="13">18</numVerses>
    <numVerses chapter="14">19</numVerses>
    <numVerses chapter="15">19</numVerses>
    <numVerses chapter="16">24</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Job</nameEnglish>
    <referenceAbbreviation>JOB</referenceAbbreviation>
    <numChapters>42</numChapters>
    <numVerses chapter="1">22</numVerses>
    <numVerses chapter="2">13</numVerses>
    <numVerses chapter="3">26</numVerses>
    <numVerses chapter="4">21</numVerses>
    <numVerses chapter="5">27</numVerses>
    <numVerses chapter="6">30</numVerses>
    <numVerses chapter="7">21</numVerses>
    <numVerses chapter="8">22</numVerses>
    <numVerses chapter="9">35</numVerses>
    <numVerses chapter="10">22</numVerses>
    <numVerses chapter="11">20</numVerses>
    <numVerses chapter="12">25</numVerses>
    <numVerses chapter="13">28</numVerses>
    <numVerses chapter="14">22</numVerses>
    <numVerses chapter="15">35</numVerses>
    <numVerses chapter="16">23</numVerses>
    <numVerses chapter="17">16</numVerses>
    <numVerses chapter="18">21</numVerses>
    <numVerses chapter="19">29</numVerses>
    <numVerses chapter="20">29</numVerses>
    <numVerses chapter="21">34</numVerses>
    <numVerses chapter="22">30</numVerses>
    <numVerses chapter="23">17</numVerses>
    <numVerses chapter="24">25</numVerses>
    <numVerses chapter="25">6</numVerses>
    <numVerses chapter="26">14</numVerses>
    <numVerses chapter="27">23</numVerses>
    <numVerses chapter="28">28</numVerses>
    <numVerses chapter="29">25</numVerses>
    <numVerses chapter="30">31</numVerses>
    <numVerses chapter="31">40</numVerses>
    <numVerses chapter="32">22</numVerses>
    <numVerses chapter="33">33</numVerses>
    <numVerses chapter="34">37</numVerses>
    <numVerses chapter="35">16</numVerses>
    <numVerses chapter="36">33</numVerses>
    <numVerses chapter="37">24</numVerses>
    <numVerses chapter="38">41</numVerses>
    <numVerses chapter="39">35</numVerses>
    <numVerses chapter="40">28</numVerses>
    <numVerses chapter="41">25</numVerses>
    <numVerses chapter="42">16</numVerses>
  </BibleBookVersification>
  <BibleBookVersification>
    <nameEnglish>Psalms</nameEnglish>
    <referenceAbbreviation>PSA</referenceAbbreviation>
    <numChapters>150</numChapters>
    <numVerses chapter="1">6</numVerses>
    <numVerses chapter="2">13</numVerses>
    <numVerses chapter="3">9</numVerses>
    <numVerses chapter="4">10</numVerses>
    <numVerses chapter="5">13</numVerses>
    <numVerses chapter="6">11</numVerses>
    <numVerses chapter="7">18</numVerses>
    <numVerses chapter="8">10</numVerses>
    <numVerses chapter="9">39</numVerses>
    <numVerses chapter="10">8</numVerses>
    <numVerses chapter="11">9</numVerses>
    <numVerses chapter="12">6</numVerses>
    <numVerses chapter="13">7</numVerses>
    <numVerses chapter="14">5</numVerses>
    <numVerses chapter="15">10</numVerses>
    <numVerses chapter="16">15</numVerses>
    <numVerses chapter="17">51</numVerses>
    <numVerses chapter="18">15</numVerses>
    <numVerses chapter="19">10</numVerses>
    <numVerses chapter="20">14</numVerses>
    <numVerses chapter="21">32</numVerses>
    <numVerses chapter="22">6</numVerses>
    <numVerses chapter="23">10</numVerses>
    <numVerses chapter="24">22</numVerses>
    <numVerses chapter="25">12</numVerses>
    <numVerses chapter="26">14</numVerses>
    <numVerses chapter="27">9</numVerses>
    <numVerses chapter="28">11</numVerses>
    <numVerses chapter="29">13</numVerses>
    <numVerses chapter="30">25</numVerses>
    <numVerses chapter="31">11</numVerses>
    <numVerses chapter="32">22</numVerses>
    <numVerses chapter="33">23</numVerses>
    <numVerses chapter="34">28</numVerses>
    <numVerses chapter="35">13</numVerses>
    <numVerses chapter="36">40</numVerses>
    <numVerses chapter="37">23</numVerses>
    <numVerses chapter="38">14</numVerses>
    <numVerses chapter="39">18</numVerses>
    <numVerses chapter="40">14</numVerses>
    <numVerses chapter="41">12</numVerses>
    <numVerses chapter="42">5</numVerses>
    <numVerses chapter="43">26</numVerses>
    <numVerses chapter="44">18</numVerses>
    <numVerses chapter="45">12</numVerses>
    <numVerses chapter="46">10</numVerses>
    <numVerses chapter="47">15</numVerses>
    <numVerses chapter="48">21</numVerses>
    <numVerses chapter="49">23</numVerses>
    <numVerses chapter="50">21</numVerses>
    <numVerses chapter="51">11</numVerses>
    <numVerses chapter="52">7</numVerses>
    <numVerses chapter="53">9</numVerses>
    <numVerses chapter="54">24</numVerses>
    <numVerses chapter="55">13</numVerses>
    <numVerses chapter="56">12</numVerses>
    <numVerses chapter="57">12</numVerses>
    <numVerses chapter="58">18</numVerses>
    <numVerses chapter="59">14</numVerses>
    <numVerses chapter="60">9</numVerses>
    <numVerses chapter="61">13</numVerses>
    <numVerses chapter="62">12</numVerses>
    <numVerses chapter="63">11</numVerses>
    <numVerses chapter="64">14</numVerses>
    <numVerses chapter="65">20</numVerses>
    <numVerses chapter="66">8</numVerses>
    <numVerses chapter="67">36</numVerses>
    <numVerses chapter="68">37</numVerses>
    <numVerses chapter="69">6</numVerses>
    <numVerses chapter="70">24</numVerses>
    <numVerses chapter="71">20</numVerses>
    <numVerses chapter="72">28</numVerses>
    <numVerses chapter="73">23</numVerses>
    <numVerses chapter="74">11</numVerses>
    <numVerses chapter="75">13</numVerses>
    <numVerses chapter="76">21</numVerses>
    <numVerses chapter="77">72</numVerses>
    <numVerses chapter="78">13</numVerses>
    <numVerses chapter="79">20</numVerses>
    <numVerses chapter="80">17</numVerses>
    <numVerses chapter="81">8</numVerses>
    <numVerses chapter="82">19</numVerses>