<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible book reference abbreviations in the order that they are included in the given publication.
    The list of the available 3-character book reference abbreviations can be found in BibleBooksCodes.xml
    An ascending id number is also included as an attribute for convenience.

Only the ORDER of books is important. Not all books listed here are necessarily included in any one publication.

The data entries in this file are language agnostic, i.e., the information can apply to a publication in any language.

The data is preceded by a header of the same format as an OSIS header.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleBookOrderSystem [
    <!ELEMENT BibleBookOrderSystem (header,book+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|cre|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT book (#PCDATA)>
            <!ATTLIST book id CDATA #REQUIRED>
]>

<BibleBookOrderSystem>

  <header>
    <work>
      <version>0.31</version>
      <date>2012-09-07</date>
      <title>Septuagint (LXX) book order</title>
      <contributor role="com">Robert Hunt</contributor>
      <identifier type="URL">http://lc.bfbs.org.uk/request.php?canonicalissuesinparatext.pdf</identifier>
      <identifier type="URL">http://en.wikipedia.org/wiki/Septuagint#Table_of_books</identifier>
      <rights>Public Domain</rights>
    </work>
  </header>

  <book id="1">GEN</book>
  <book id="2">EXO</book>
  <book id="3">LEV</book>
  <book id="4">NUM</book>
  <book id="5">DEU</book>
  <book id="6">JOS</book>
  <book id="7">JDG</book>
  <book id="8">RUT</book>
  <book id="9">SA1</book>
  <book id="10">SA2</book>
  <book id="11">KI1</book>
  <book id="12">KI2</book>
  <book id="13">CH1</book>
  <book id="14">CH2</book>
  <book id="15">GES</book>
  <book id="16">EZN</book>
  <book id="17">ESG</book>
  <book id="18">JDT</book>
  <book id="19">TOB</book>
  <book id="20">MA1</book>
  <book id="21">MA2</book>
  <book id="22">MA3</book>
  <book id="23">PSA</book>
  <book id="24">PS2</book>
  <book id="25">MAN</book>
  <book id="26">JOB</book>
  <book id="27">PRO</book>
  <book id="28">ECC</book>
  <book id="29">SNG</book>
  <book id="30">WIS</book>
  <book id="31">SIR</book>
  <book id="32">PSS</book>
  <book id="33">HOS</book>
  <book id="34">AMO</book>
  <book id="35">MIC</book>
  <book id="36">JOL</book>
  <book id="37">OBA</book>
  <book id="38">JNA</book>
  <book id="39">NAH</book>
  <book id="40">HAB</book>
  <book id="41">ZEP</book>
  <book id="42">HAG</book>
  <book id="43">ZEC</book>
  <book id="44">MAL</book>
  <book id="45">ISA</book>
  <book id="46">JER</book>
  <book id="47">BAR</book>
  <book id="48">LAM</book>
  <book id="49">LJE</book>
  <book id="50">EZE</book>
  <book id="51">DNG</book>
  <book id="52">MA4</book>
</BibleBookOrderSystem>
