<?xml version="1.0" encoding="UTF-8"?>

<!--
The three lower-case letters after the first underscore in the filename should be the ISO 639-3 code for the language.
If necessary, this case be followed by another underscore and a description, e.g., eng_traditional vs eng_modern

This file contains three tables:
    BibleDivisionNames
        The standardAbbreviation attribute may be recognisable to the software, e.g., PT, OT, NT, DC, etc.
            Use forms like D1, D2, etc. if you need different divisions for the given language
        The defaultName element for this division
        The defaultAbbreviation element for this division (if we need to display it in a confined space)
        Optional inputAbbreviation elements which may be used by a user
            The defaultName and defaultAbbreviation are automatically added to this list.
            The software automatically calculates all unambiguous shortened forms.
            You can include common mispellings here.
        An includesBook line with a BBB BibleBookCode for every book included in this named division of the Bible.
            The order of the lines don't actually matter although it normally makes sense to list them in order.
    BibleBooknameLeaders
        The standardLeader attribute is the form, like 1 or 2 that might precede 1 Samuel or 2 Timothy.
            This has to match what is used in the defaultName and/or defaultAbbreviation for BibleBookNames below.
        The inputAbbreviation elements are alternative forms that a user might enter,
            e.g., I or II (Roman numerals),  or one or two (words).
    BibleBookNames
        The referenceAbbreviation attribute is the standard 3-character BBB BibleBookCode.
        The defaultName element is the standard name for this book in the given language.
        The defaultAbbreviation element for this book (if we need to display it in a confined space)
        Optional inputAbbreviation elements which may be used by a user
            The defaultName and defaultAbbreviation are automatically added to this list.
            The software automatically calculates all unambiguous shortened forms.
            You can include common mispellings here.
            The software automatically substitutes different leaders, e.g., II for 2, and removes spaces.
All of the above fields should be unique.
Information for any extra books can be included (whether or not they are used in a particular publication).

The data is preceded by a header of the same format as an OSIS header.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.
    For DTD: ? = optional (zero or one), * = zero or more, + = one or more

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleBooksNames [
    <!ELEMENT BibleBooksNames (header,BibleDivisionNames+,BibleBooknameLeaders+,BibleBookNames+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleDivisionNames (defaultName,defaultAbbreviation,inputAbbreviation*,includesBook+)>
            <!ATTLIST BibleDivisionNames standardAbbreviation CDATA #REQUIRED>
        <!ELEMENT BibleBooknameLeaders (inputAbbreviation+)>
            <!ATTLIST BibleBooknameLeaders standardLeader CDATA #REQUIRED>
        <!ELEMENT BibleBookNames (defaultName,defaultAbbreviation,inputAbbreviation*)>
            <!ATTLIST BibleBookNames referenceAbbreviation CDATA #REQUIRED>
            <!ELEMENT defaultName (#PCDATA)>
            <!ELEMENT defaultAbbreviation (#PCDATA)>
            <!ELEMENT inputAbbreviation (#PCDATA)>
            <!ELEMENT includesBook (#PCDATA)>
]>

<BibleBooksNames>

  <header>
    <work>
      <version>0.28</version>
      <date>2016-07-08</date>
      <title>Traditional English Bible books names list</title>
      <contributor role="com">Robert Hunt</contributor>
      <rights>Public Domain</rights>
    </work>
  </header>


  <BibleDivisionNames standardAbbreviation="OT">
    <defaultName>Old Testament</defaultName>
    <defaultAbbreviation>OT</defaultAbbreviation>
    <inputAbbreviation>Old Tstmnt</inputAbbreviation>
    <includesBook>GEN</includesBook>
    <includesBook>EXO</includesBook>
    <includesBook>LEV</includesBook>
    <includesBook>NUM</includesBook>
    <includesBook>DEU</includesBook>
    <includesBook>JOS</includesBook>
    <includesBook>JDG</includesBook>
    <includesBook>RUT</includesBook>
    <includesBook>SA1</includesBook>
    <includesBook>SA2</includesBook>
    <includesBook>KI1</includesBook>
    <includesBook>KI2</includesBook>
    <includesBook>CH1</includesBook>
    <includesBook>CH2</includesBook>
    <includesBook>EZR</includesBook>
    <includesBook>NEH</includesBook>
    <includesBook>EST</includesBook>
    <includesBook>JOB</includesBook>
    <includesBook>PSA</includesBook>
    <includesBook>PRO</includesBook>
    <includesBook>ECC</includesBook>
    <includesBook>SNG</includesBook>
    <includesBook>ISA</includesBook>
    <includesBook>JER</includesBook>
    <includesBook>LAM</includesBook>
    <includesBook>EZE</includesBook>
    <includesBook>DAN</includesBook>
    <includesBook>HOS</includesBook>
    <includesBook>JOL</includesBook>
    <includesBook>AMO</includesBook>
    <includesBook>OBA</includesBook>
    <includesBook>JNA</includesBook>
    <includesBook>MIC</includesBook>
    <includesBook>NAH</includesBook>
    <includesBook>HAB</includesBook>
    <includesBook>ZEP</includesBook>
    <includesBook>HAG</includesBook>
    <includesBook>ZEC</includesBook>
    <includesBook>MAL</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="PT">
    <defaultName>Pentateuch</defaultName>
    <defaultAbbreviation>Pent</defaultAbbreviation>
    <inputAbbreviation>Pnttch</inputAbbreviation>
    <inputAbbreviation>Torah</inputAbbreviation>
    <inputAbbreviation>Trh</inputAbbreviation>
    <inputAbbreviation>Moses' books</inputAbbreviation>
    <inputAbbreviation>Books of Moses</inputAbbreviation>
    <inputAbbreviation>Bks of Moses</inputAbbreviation>
    <includesBook>GEN</includesBook>
    <includesBook>EXO</includesBook>
    <includesBook>LEV</includesBook>
    <includesBook>NUM</includesBook>
    <includesBook>DEU</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="MJ">
    <defaultName>Major Prophets</defaultName>
    <defaultAbbreviation>MajProps</defaultAbbreviation>
    <inputAbbreviation>Mjr Prphts</inputAbbreviation>
    <includesBook>ISA</includesBook>
    <includesBook>JER</includesBook>
    <includesBook>LAM</includesBook>
    <includesBook>EZE</includesBook>
    <includesBook>DAN</includesBook>
    <includesBook>BAR</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="MN">
    <defaultName>Minor Prophets</defaultName>
    <defaultAbbreviation>MinProp</defaultAbbreviation>
    <inputAbbreviation>Mnr Prphts</inputAbbreviation>
    <includesBook>HOS</includesBook>
    <includesBook>JOL</includesBook>
    <includesBook>AMO</includesBook>
    <includesBook>OBA</includesBook>
    <includesBook>JNA</includesBook>
    <includesBook>MIC</includesBook>
    <includesBook>NAH</includesBook>
    <includesBook>HAB</includesBook>
    <includesBook>ZEP</includesBook>
    <includesBook>HAG</includesBook>
    <includesBook>ZEC</includesBook>
    <includesBook>MAL</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="NT">
    <defaultName>New Testament</defaultName>
    <defaultAbbreviation>NT</defaultAbbreviation>
    <inputAbbreviation>Nw Tstmnt</inputAbbreviation>
    <includesBook>MAT</includesBook>
    <includesBook>MRK</includesBook>
    <includesBook>LUK</includesBook>
    <includesBook>JHN</includesBook>
    <includesBook>ACT</includesBook>
    <includesBook>ROM</includesBook>
    <includesBook>CO1</includesBook>
    <includesBook>CO2</includesBook>
    <includesBook>GAL</includesBook>
    <includesBook>EPH</includesBook>
    <includesBook>PHP</includesBook>
    <includesBook>COL</includesBook>
    <includesBook>TH1</includesBook>
    <includesBook>TH2</includesBook>
    <includesBook>TI1</includesBook>
    <includesBook>TI2</includesBook>
    <includesBook>TIT</includesBook>
    <includesBook>PHM</includesBook>
    <includesBook>HEB</includesBook>
    <includesBook>JAM</includesBook>
    <includesBook>PE1</includesBook>
    <includesBook>PE2</includesBook>
    <includesBook>JN1</includesBook>
    <includesBook>JN2</includesBook>
    <includesBook>JN3</includesBook>
    <includesBook>JDE</includesBook>
    <includesBook>REV</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="GO">
    <defaultName>Gospels</defaultName>
    <defaultAbbreviation>Gosp</defaultAbbreviation>
    <inputAbbreviation>Gspls</inputAbbreviation>
    <includesBook>MAT</includesBook>
    <includesBook>MRK</includesBook>
    <includesBook>LUK</includesBook>
    <includesBook>JHN</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="PL">
    <defaultName>Pauline Epistles</defaultName>
    <defaultAbbreviation>EpPaul</defaultAbbreviation>
    <inputAbbreviation>Paul's epistles</inputAbbreviation>
    <inputAbbreviation>Epistles of Paul</inputAbbreviation>
    <inputAbbreviation>Ep of Paul</inputAbbreviation>
    <inputAbbreviation>Letters of Paul</inputAbbreviation>
    <inputAbbreviation>Ltrs of Paul</inputAbbreviation>
    <inputAbbreviation>Paul's letters</inputAbbreviation>
    <inputAbbreviation>Paul's ltrs</inputAbbreviation>
    <includesBook>ROM</includesBook>
    <includesBook>CO1</includesBook>
    <includesBook>CO2</includesBook>
    <includesBook>GAL</includesBook>
    <includesBook>EPH</includesBook>
    <includesBook>PHP</includesBook>
    <includesBook>COL</includesBook>
    <includesBook>TH1</includesBook>
    <includesBook>TH2</includesBook>
    <includesBook>TI1</includesBook>
    <includesBook>TI2</includesBook>
    <includesBook>TIT</includesBook>
    <includesBook>PHM</includesBook>
    <!-- We'll include Hebrews here too by default -->
    <includesBook>HEB</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="DC">
    <defaultName>Deuterocanon</defaultName>
    <defaultAbbreviation>DC</defaultAbbreviation>
    <inputAbbreviation>DtrCnn</inputAbbreviation>
    <inputAbbreviation>Apocrypha</inputAbbreviation>
    <inputAbbreviation>Apcrypha</inputAbbreviation>
    <includesBook>TOB</includesBook>
    <includesBook>JDT</includesBook>
    <includesBook>ESG</includesBook>
    <includesBook>WIS</includesBook>
    <includesBook>SIR</includesBook>
    <includesBook>LJE</includesBook>
    <includesBook>PAZ</includesBook>
    <includesBook>SUS</includesBook>
    <includesBook>BEL</includesBook>
    <includesBook>MA1</includesBook>
    <includesBook>MA2</includesBook>
    <includesBook>GES</includesBook>
    <includesBook>LES</includesBook>
    <includesBook>MAN</includesBook>
  </BibleDivisionNames>


  <BibleBooknameLeaders standardLeader="1">
    <inputAbbreviation>I</inputAbbreviation>
    <inputAbbreviation>First</inputAbbreviation>
    <inputAbbreviation>Frst</inputAbbreviation>
    <inputAbbreviation>1st</inputAbbreviation>
    <inputAbbreviation>One</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="2">
    <inputAbbreviation>II</inputAbbreviation>
    <inputAbbreviation>Second</inputAbbreviation>
    <inputAbbreviation>Scnd</inputAbbreviation>
    <inputAbbreviation>2nd</inputAbbreviation>
    <inputAbbreviation>Two</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="3">
    <inputAbbreviation>III</inputAbbreviation>
    <inputAbbreviation>Third</inputAbbreviation>
    <inputAbbreviation>Thrd</inputAbbreviation>
    <inputAbbreviation>3rd</inputAbbreviation>
    <inputAbbreviation>Three</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="4">
    <inputAbbreviation>IV</inputAbbreviation>
    <inputAbbreviation>Fourth</inputAbbreviation>
    <inputAbbreviation>Forth</inputAbbreviation>
    <inputAbbreviation>Frth</inputAbbreviation>
    <inputAbbreviation>4th</inputAbbreviation>
    <inputAbbreviation>Four</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="5">
    <inputAbbreviation>V</inputAbbreviation>
    <inputAbbreviation>Fifth</inputAbbreviation>
    <inputAbbreviation>Ffth</inputAbbreviation>
    <inputAbbreviation>5th</inputAbbreviation>
    <inputAbbreviation>Five</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="6">
    <inputAbbreviation>VI</inputAbbreviation>
    <inputAbbreviation>Sixth</inputAbbreviation>
    <inputAbbreviation>Sxth</inputAbbreviation>
    <inputAbbreviation>6th</inputAbbreviation>
    <inputAbbreviation>Six</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="Saint">
    <inputAbbreviation>Snt</inputAbbreviation>
    <inputAbbreviation>St</inputAbbreviation>
    <inputAbbreviation>Snt.</inputAbbreviation>
    <inputAbbreviation>St.</inputAbbreviation>
  </BibleBooknameLeaders>


  <BibleBookNames referenceAbbreviation="GEN">
    <defaultName>Genesis</defaultName>
    <defaultAbbreviation>Gen</defaultAbbreviation>
    <inputAbbreviation>Gnss</inputAbbreviation>
    <inputAbbreviation>1 Moses</inputAbbreviation>
    <inputAbbreviation>1 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EXO">
    <defaultName>Exodus</defaultName>
    <defaultAbbreviation>Exo</defaultAbbreviation>
    <inputAbbreviation>Exds</inputAbbreviation>
    <inputAbbreviation>2 Moses</inputAbbreviation>
    <inputAbbreviation>2 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="LEV">
    <defaultName>Leviticus</defaultName>
    <defaultAbbreviation>Lev</defaultAbbreviation>
    <inputAbbreviation>Lvtcs</inputAbbreviation>
    <inputAbbreviation>3 Moses</inputAbbreviation>
    <inputAbbreviation>3 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="NUM">
    <defaultName>Numbers</defaultName>
    <defaultAbbreviation>Num</defaultAbbreviation>
    <inputAbbreviation>Nmbrs</inputAbbreviation>
    <inputAbbreviation>4 Moses</inputAbbreviation>
    <inputAbbreviation>4 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="DEU">
    <defaultName>Deuteronomy</defaultName>
    <defaultAbbreviation>Deu</defaultAbbreviation>
    <inputAbbreviation>Dtrnmy</inputAbbreviation>
    <inputAbbreviation>5 Moses</inputAbbreviation>
    <inputAbbreviation>5 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JOS">
    <defaultName>Joshua</defaultName>
    <defaultAbbreviation>Josh</defaultAbbreviation>
    <inputAbbreviation>Jsh</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JDG">
    <defaultName>Judges</defaultName>
    <defaultAbbreviation>Jdg</defaultAbbreviation>
    <inputAbbreviation>Jdgs</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="RUT">
    <defaultName>Ruth</defaultName>
    <defaultAbbreviation>Rut</defaultAbbreviation>
    <inputAbbreviation>Rth</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="SA1">
    <defaultName>1 Samuel</defaultName>
    <defaultAbbreviation>1 Sam</defaultAbbreviation>
    <inputAbbreviation>1 Sml</inputAbbreviation>
    <inputAbbreviation>1 Sl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="SA2">
    <defaultName>2 Samuel</defaultName>
    <defaultAbbreviation>2 Sam</defaultAbbreviation>
    <inputAbbreviation>2 Sml</inputAbbreviation>
    <inputAbbreviation>2 Sl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="KI1">
    <defaultName>1 Kings</defaultName>
    <defaultAbbreviation>1 Kgs</defaultAbbreviation>
    <inputAbbreviation>1 Kngs</inputAbbreviation>
    <inputAbbreviation>1 Ks</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="KI2">
    <defaultName>2 Kings</defaultName>
    <defaultAbbreviation>2 Kgs</defaultAbbreviation>
    <inputAbbreviation>2 Kngs</inputAbbreviation>
    <inputAbbreviation>2 Ks</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CH1">
    <defaultName>1 Chronicles</defaultName>
    <defaultAbbreviation>1 Chr</defaultAbbreviation>
    <inputAbbreviation>1 Chrnc</inputAbbreviation>
    <inputAbbreviation>1 Cronic</inputAbbreviation>
    <inputAbbreviation>1 Crnc</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CH2">
    <defaultName>2 Chronicles</defaultName>
    <defaultAbbreviation>2 Chr</defaultAbbreviation>
    <inputAbbreviation>2 Chrnc</inputAbbreviation>
    <inputAbbreviation>2 Cronic</inputAbbreviation>
    <inputAbbreviation>2 Crnc</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EZR">
    <defaultName>Ezra</defaultName>
    <defaultAbbreviation>Ezr</defaultAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="NEH">
    <defaultName>Nehemiah</defaultName>
    <defaultAbbreviation>Neh</defaultAbbreviation>
    <inputAbbreviation>Nhmh</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EST">
    <defaultName>Esther</defaultName>
    <defaultAbbreviation>Est</defaultAbbreviation>
    <inputAbbreviation>Esthr</inputAbbreviation>
    <inputAbbreviation>Estr</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JOB">
    <defaultName>Job</defaultName>
    <defaultAbbreviation>Job</defaultAbbreviation>
    <inputAbbreviation>Jb</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PSA">
    <defaultName>Psalms</defaultName>
    <defaultAbbreviation>Psa</defaultAbbreviation>
    <inputAbbreviation>Pslms</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PRO">
    <defaultName>Proverbs</defaultName>
    <defaultAbbreviation>Pro</defaultAbbreviation>
    <inputAbbreviation>Prvrbs</inputAbbreviation>
    <inputAbbreviation>Prvbs</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ECC">
    <defaultName>Ecclesiastes</defaultName>
    <defaultAbbreviation>Ecc</defaultAbbreviation>
    <inputAbbreviation>Ecclsts</inputAbbreviation>
    <inputAbbreviation>Qoheleth</inputAbbreviation>
    <inputAbbreviation>Qhlth</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="SNG">
    <defaultName>Song of Solomon</defaultName>
    <defaultAbbreviation>Sng</defaultAbbreviation>
    <inputAbbreviation>Sng of Slmn</inputAbbreviation>
    <inputAbbreviation>Song of Songs</inputAbbreviation>
    <inputAbbreviation>Sng of Sngs</inputAbbreviation>
    <inputAbbreviation>SoS</inputAbbreviation>
    <inputAbbreviation>SS</inputAbbreviation>
    <inputAbbreviation>Canticle of Canticles</inputAbbreviation>
    <inputAbbreviation>Cntcl of Cntcl</inputAbbreviation>
    <inputAbbreviation>CoC</inputAbbreviation>
    <inputAbbreviation>CC</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ISA">
    <defaultName>Isaiah</defaultName>
    <defaultAbbreviation>Isa</defaultAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JER">
    <defaultName>Jeremiah</defaultName>
    <defaultAbbreviation>Jer</defaultAbbreviation>
    <inputAbbreviation>Jrmh</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="LAM">
    <defaultName>Lamentations</defaultName>
    <defaultAbbreviation>Lam</defaultAbbreviation>
    <inputAbbreviation>Lmnts</inputAbbreviation>
    <inputAbbreviation>Lamentations of Jeremiah</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EZE">
    <defaultName>Ezekiel</defaultName>
    <defaultAbbreviation>Eze</defaultAbbreviation>
    <inputAbbreviation>Ezkl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="DAN">
    <defaultName>Daniel</defaultName>
    <defaultAbbreviation>Dan</defaultAbbreviation>
    <inputAbbreviation>Dnl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HOS">
    <defaultName>Hosea</defaultName>
    <defaultAbbreviation>Hos</defaultAbbreviation>
    <inputAbbreviation>Hs</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JOL">
    <defaultName>Joel</defaultName>
    <defaultAbbreviation>Joel</defaultAbbreviation>
    <inputAbbreviation>Jl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="AMO">
    <defaultName>Amos</defaultName>
    <defaultAbbreviation>Amos</defaultAbbreviation>
    <inputAbbreviation>Ams</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="OBA">
    <defaultName>Obadiah</defaultName>
    <defaultAbbreviation>Oba</defaultAbbreviation>
    <inputAbbreviation>Obdh</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JNA">
    <defaultName>Jonah</defaultName>
    <defaultAbbreviation>Jon</defaultAbbreviation>
    <inputAbbreviation>Jnh</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="MIC">
    <defaultName>Micah</defaultName>
    <defaultAbbreviation>Mic</defaultAbbreviation>
    <inputAbbreviation>Mcah</inputAbbreviation>
    <inputAbbreviation>Mich</inputAbbreviation>
    <inputAbbreviation>Mch</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="NAH">
    <defaultName>Nahum</defaultName>
    <defaultAbbreviation>Nah</defaultAbbreviation>
    <inputAbbreviation>Nahm</inputAbbreviation>
    <inputAbbreviation>Nhum</inputAbbreviation>
    <inputAbbreviation>Nhm</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HAB">
    <defaultName>Habakkuk</defaultName>
    <defaultAbbreviation>Hab</defaultAbbreviation>
    <inputAbbreviation>Hbkk</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>Habbakkuk</inputAbbreviation>
    <inputAbbreviation>Habbakuk</inputAbbreviation>
    <inputAbbreviation>Habakuk</inputAbbreviation>
    <inputAbbreviation>Hbbkk</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ZEP">
    <defaultName>Zephaniah</defaultName>
    <defaultAbbreviation>Zep</defaultAbbreviation>
    <inputAbbreviation>Zphnh</inputAbbreviation>
    <inputAbbreviation>Zefaniah</inputAbbreviation>
    <inputAbbreviation>Zfnh</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HAG">
    <defaultName>Haggai</defaultName>
    <defaultAbbreviation>Hag</defaultAbbreviation>
    <inputAbbreviation>Hgg</inputAbbreviation>
    <inputAbbreviation>Hagai</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ZEC">
    <defaultName>Zechariah</defaultName>
    <defaultAbbreviation>Zec</defaultAbbreviation>
    <inputAbbreviation>Zchrh</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="MAL">
    <defaultName>Malachi</defaultName>
    <defaultAbbreviation>Mal</defaultAbbreviation>
    <inputAbbreviation>Mlchi</inputAbbreviation>
  </BibleBookNames>

  <BibleBookNames referenceAbbreviation="MAT">
    <defaultName>Matthew</defaultName>
    <defaultAbbreviation>Mat</defaultAbbreviation>
    <inputAbbreviation>Mtthw</inputAbbreviation>
    <inputAbbreviation>Mthw</inputAbbreviation>
    <inputAbbreviation>Mtw</inputAbbreviation>
    <inputAbbreviation>Mw</inputAbbreviation>
    <inputAbbreviation>Saint Matthew</inputAbbreviation>
    <inputAbbreviation>Saint Mtthw</inputAbbreviation>
    <inputAbbreviation>Saint Mthw</inputAbbreviation>
    <inputAbbreviation>Saint Mtw</inputAbbreviation>
    <inputAbbreviation>Saint Mw</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="MRK">
    <defaultName>Mark</defaultName>
    <defaultAbbreviation>Mrk</defaultAbbreviation>
    <inputAbbreviation>Mk</inputAbbreviation>
    <inputAbbreviation>Saint Mark</inputAbbreviation>
    <inputAbbreviation>Saint Mrk</inputAbbreviation>
    <inputAbbreviation>Saint Mk</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="LUK">
    <defaultName>Luke</defaultName>
    <defaultAbbreviation>Luk</defaultAbbreviation>
    <inputAbbreviation>Lke</inputAbbreviation>
    <inputAbbreviation>Saint Luke</inputAbbreviation>
    <inputAbbreviation>Saint Lk</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JHN">
    <defaultName>John</defaultName>
    <defaultAbbreviation>Jhn</defaultAbbreviation>
    <inputAbbreviation>Jn</inputAbbreviation>
    <inputAbbreviation>Saint John</inputAbbreviation>
    <inputAbbreviation>Saint Jhn</inputAbbreviation>
    <inputAbbreviation>Saint Jn</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ACT">
    <defaultName>Acts</defaultName>
    <defaultAbbreviation>Act</defaultAbbreviation>
    <inputAbbreviation>Ats</inputAbbreviation>
    <inputAbbreviation>Acts of the Apostles</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ROM">
    <defaultName>Romans</defaultName>
    <defaultAbbreviation>Rom</defaultAbbreviation>
    <inputAbbreviation>Rmns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CO1">
    <defaultName>1 Corinthians</defaultName>
    <defaultAbbreviation>1 Cor</defaultAbbreviation>
    <inputAbbreviation>1 Crnthns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CO2">
    <defaultName>2 Corinthians</defaultName>
    <defaultAbbreviation>2 Cor</defaultAbbreviation>
    <inputAbbreviation>2 Crnthns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="GAL">
    <defaultName>Galatians</defaultName>
    <defaultAbbreviation>Gal</defaultAbbreviation>
    <inputAbbreviation>Gltns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EPH">
    <defaultName>Ephesians</defaultName>
    <defaultAbbreviation>Eph</defaultAbbreviation>
    <inputAbbreviation>Ephsns</inputAbbreviation>
    <inputAbbreviation>Efsns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PHP">
    <defaultName>Philippians</defaultName>
    <defaultAbbreviation>Php</defaultAbbreviation>
    <inputAbbreviation>Phlppns</inputAbbreviation>
    <inputAbbreviation>Phlpns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>Phillippians</inputAbbreviation>
    <inputAbbreviation>Phillipians</inputAbbreviation>
    <inputAbbreviation>Philipians</inputAbbreviation>
    <inputAbbreviation>Flppns</inputAbbreviation>
    <inputAbbreviation>Flpns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="COL">
    <defaultName>Colossians</defaultName>
    <defaultAbbreviation>Col</defaultAbbreviation>
    <inputAbbreviation>Clssns</inputAbbreviation>
    <inputAbbreviation>Clsns</inputAbbreviation>
    <inputAbbreviation>Cllssns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>Collosians</inputAbbreviation>
    <inputAbbreviation>Collossians</inputAbbreviation>
    <inputAbbreviation>Colosians</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TH1">
    <defaultName>1 Thessalonians</defaultName>
    <defaultAbbreviation>1 Thess</defaultAbbreviation>
    <inputAbbreviation>1 Thsslns</inputAbbreviation>
    <inputAbbreviation>1 Thslns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>1 Thesallonians</inputAbbreviation>
    <inputAbbreviation>1 Thessallonians</inputAbbreviation>
    <inputAbbreviation>1 Thesalonians</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TH2">
    <defaultName>2 Thessalonians</defaultName>
    <defaultAbbreviation>2 Thess</defaultAbbreviation>
    <inputAbbreviation>2 Thsslns</inputAbbreviation>
    <inputAbbreviation>2 Thslns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>2 Thesallonians</inputAbbreviation>
    <inputAbbreviation>2 Thessallonians</inputAbbreviation>
    <inputAbbreviation>2 Thesalonians</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TI1">
    <defaultName>1 Timothy</defaultName>
    <defaultAbbreviation>1 Tim</defaultAbbreviation>
    <inputAbbreviation>1 Tmthy</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TI2">
    <defaultName>2 Timothy</defaultName>
    <defaultAbbreviation>2 Tim</defaultAbbreviation>
    <inputAbbreviation>2 Tmthy</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TIT">
    <defaultName>Titus</defaultName>
    <defaultAbbreviation>Tit</defaultAbbreviation>
    <inputAbbreviation>Tts</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PHM">
    <defaultName>Philemon</defaultName>
    <defaultAbbreviation>Phm</defaultAbbreviation>
    <inputAbbreviation>Phlmn</inputAbbreviation>
    <inputAbbreviation>Flmn</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HEB">
    <defaultName>Hebrews</defaultName>
    <defaultAbbreviation>Heb</defaultAbbreviation>
    <inputAbbreviation>Hbrws</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JAM">
    <defaultName>James</defaultName>