<?xml version="1.0" encoding="UTF-8"?>

<!--
The three lower-case letters after the first underscore in the filename should be the ISO 639-3 code for the language.
If necessary, this case be followed by another underscore and a description, e.g., eng_traditional vs eng_modern

This file contains three tables:
    BibleDivisionNames
        The standardAbbreviation attribute may be recognisable to the software, e.g., PT, OT, NT, DC, etc.
            Use forms like D1, D2, etc. if you need different divisions for the given language
        The defaultName element for this division
        The defaultAbbreviation element for this division (if we need to display it in a confined space)
        Optional inputAbbreviation elements which may be used by a user
            The defaultName and defaultAbbreviation are automatically added to this list.
            The software automatically calculates all unambiguous shortened forms.
            You can include common mispellings here.
        An includesBook line with a BBB BibleBookCode for every book included in this named division of the Bible.
            The order of the lines don't actually matter although it normally makes sense to list them in order.
    BibleBooknameLeaders
        The standardLeader attribute is the form, like 1 or 2 that might precede 1 Samuel or 2 Timothy.
            This has to match what is used in the defaultName and/or defaultAbbreviation for BibleBookNames below.
        The inputAbbreviation elements are alternative forms that a user might enter,
            e.g., I or II (Roman numerals),  or one or two (words).
    BibleBookNames
        The referenceAbbreviation attribute is the standard 3-character BBB BibleBookCode.
        The defaultName element is the standard name for this book in the given language.
        The defaultAbbreviation element for this book (if we need to display it in a confined space)
        Optional inputAbbreviation elements which may be used by a user
            The defaultName and defaultAbbreviation are automatically added to this list.
            The software automatically calculates all unambiguous shortened forms.
            You can include common mispellings here.
            The software automatically substitutes different leaders, e.g., II for 2, and removes spaces.
All of the above fields should be unique.
Information for any extra books can be included (whether or not they are used in a particular publication).

The data is preceded by a header of the same format as an OSIS header.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.
    For DTD: ? = optional (zero or one), * = zero or more, + = one or more

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleBooksNames [
    <!ELEMENT BibleBooksNames (header,BibleDivisionNames+,BibleBooknameLeaders+,BibleBookNames+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleDivisionNames (defaultName,defaultAbbreviation,inputAbbreviation*,includesBook+)>
            <!ATTLIST BibleDivisionNames standardAbbreviation CDATA #REQUIRED>
        <!ELEMENT BibleBooknameLeaders (inputAbbreviation+)>
            <!ATTLIST BibleBooknameLeaders standardLeader CDATA #REQUIRED>
        <!ELEMENT BibleBookNames (defaultName,defaultAbbreviation,inputAbbreviation*)>
            <!ATTLIST BibleBookNames referenceAbbreviation CDATA #REQUIRED>
            <!ELEMENT defaultName (#PCDATA)>
            <!ELEMENT defaultAbbreviation (#PCDATA)>
            <!ELEMENT inputAbbreviation (#PCDATA)>
            <!ELEMENT includesBook (#PCDATA)>
]>

<BibleBooksNames>

  <header>
    <work>
      <version>0.02</version>
      <date>2016-06-23</date>
      <title>Traditional Spanish Bible books names list</title>
      <contributor role="com">Robert Hunt</contributor>
      <rights>Public Domain</rights>
    </work>
  </header>


  <BibleDivisionNames standardAbbreviation="OT">
    <defaultName>XXX-SPA-Ancien Testament</defaultName>
    <defaultAbbreviation>XXX-SPA-AT</defaultAbbreviation>
    <inputAbbreviation>XXX-SPA-L'Ancien Testament</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-L'Ancien Tstmnt</inputAbbreviation>
    <includesBook>GEN</includesBook>
    <includesBook>EXO</includesBook>
    <includesBook>LEV</includesBook>
    <includesBook>NUM</includesBook>
    <includesBook>DEU</includesBook>
    <includesBook>JOS</includesBook>
    <includesBook>JDG</includesBook>
    <includesBook>RUT</includesBook>
    <includesBook>SA1</includesBook>
    <includesBook>SA2</includesBook>
    <includesBook>KI1</includesBook>
    <includesBook>KI2</includesBook>
    <includesBook>CH1</includesBook>
    <includesBook>CH2</includesBook>
    <includesBook>EZR</includesBook>
    <includesBook>NEH</includesBook>
    <includesBook>EST</includesBook>
    <includesBook>JOB</includesBook>
    <includesBook>PSA</includesBook>
    <includesBook>PRO</includesBook>
    <includesBook>ECC</includesBook>
    <includesBook>SNG</includesBook>
    <includesBook>ISA</includesBook>
    <includesBook>JER</includesBook>
    <includesBook>LAM</includesBook>
    <includesBook>EZE</includesBook>
    <includesBook>DAN</includesBook>
    <includesBook>HOS</includesBook>
    <includesBook>JOL</includesBook>
    <includesBook>AMO</includesBook>
    <includesBook>OBA</includesBook>
    <includesBook>JNA</includesBook>
    <includesBook>MIC</includesBook>
    <includesBook>NAH</includesBook>
    <includesBook>HAB</includesBook>
    <includesBook>ZEP</includesBook>
    <includesBook>HAG</includesBook>
    <includesBook>ZEC</includesBook>
    <includesBook>MAL</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="PT">
    <defaultName>XXX-SPA-Pentateuch</defaultName>
    <defaultAbbreviation>XXX-SPA-Pent</defaultAbbreviation>
    <inputAbbreviation>XXX-SPA-Pnttch</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Torah</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Trh</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Moses' books</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Books of Moses</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Bks of Moses</inputAbbreviation>
    <includesBook>GEN</includesBook>
    <includesBook>EXO</includesBook>
    <includesBook>LEV</includesBook>
    <includesBook>NUM</includesBook>
    <includesBook>DEU</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="MJ">
    <defaultName>XXX-SPA-Major Prophets</defaultName>
    <defaultAbbreviation>XXX-SPA-MajProps</defaultAbbreviation>
    <inputAbbreviation>XXX-SPA-Mjr Prphts</inputAbbreviation>
    <includesBook>ISA</includesBook>
    <includesBook>JER</includesBook>
    <includesBook>LAM</includesBook>
    <includesBook>EZE</includesBook>
    <includesBook>DAN</includesBook>
    <includesBook>BAR</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="MN">
    <defaultName>XXX-SPA-Minor Prophets</defaultName>
    <defaultAbbreviation>XXX-SPA-MinProp</defaultAbbreviation>
    <inputAbbreviation>XXX-SPA-Mnr Prphts</inputAbbreviation>
    <includesBook>HOS</includesBook>
    <includesBook>JOL</includesBook>
    <includesBook>AMO</includesBook>
    <includesBook>OBA</includesBook>
    <includesBook>JNA</includesBook>
    <includesBook>MIC</includesBook>
    <includesBook>NAH</includesBook>
    <includesBook>HAB</includesBook>
    <includesBook>ZEP</includesBook>
    <includesBook>HAG</includesBook>
    <includesBook>ZEC</includesBook>
    <includesBook>MAL</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="NT">
    <defaultName>XXX-SPA-Nouveau Testament</defaultName>
    <defaultAbbreviation>XXX-SPA-NT</defaultAbbreviation>
    <inputAbbreviation>XXX-SPA-Le Nouveau Testament</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Nv Tstmnt</inputAbbreviation>
    <includesBook>MAT</includesBook>
    <includesBook>MRK</includesBook>
    <includesBook>LUK</includesBook>
    <includesBook>JHN</includesBook>
    <includesBook>ACT</includesBook>
    <includesBook>ROM</includesBook>
    <includesBook>CO1</includesBook>
    <includesBook>CO2</includesBook>
    <includesBook>GAL</includesBook>
    <includesBook>EPH</includesBook>
    <includesBook>PHP</includesBook>
    <includesBook>COL</includesBook>
    <includesBook>TH1</includesBook>
    <includesBook>TH2</includesBook>
    <includesBook>TI1</includesBook>
    <includesBook>TI2</includesBook>
    <includesBook>TIT</includesBook>
    <includesBook>PHM</includesBook>
    <includesBook>HEB</includesBook>
    <includesBook>JAM</includesBook>
    <includesBook>PE1</includesBook>
    <includesBook>PE2</includesBook>
    <includesBook>JN1</includesBook>
    <includesBook>JN2</includesBook>
    <includesBook>JN3</includesBook>
    <includesBook>JDE</includesBook>
    <includesBook>REV</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="GO">
    <defaultName>XXX-SPA-Gospels</defaultName>
    <defaultAbbreviation>XXX-SPA-Gosp</defaultAbbreviation>
    <inputAbbreviation>XXX-SPA-Gspls</inputAbbreviation>
    <includesBook>MAT</includesBook>
    <includesBook>MRK</includesBook>
    <includesBook>LUK</includesBook>
    <includesBook>JHN</includesBook>
  </BibleDivisionNames>
  <BibleDivisionNames standardAbbreviation="PL">
    <defaultName>XXX-SPA-Pauline Epistles</defaultName>
    <defaultAbbreviation>XXX-SPA-EpPaul</defaultAbbreviation>
    <inputAbbreviation>XXX-SPA-Paul's epistles</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Epistles of Paul</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Ep of Paul</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Letters of Paul</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Ltrs of Paul</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Paul's letters</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Paul's ltrs</inputAbbreviation>
    <includesBook>ROM</includesBook>
    <includesBook>CO1</includesBook>
    <includesBook>CO2</includesBook>
    <includesBook>GAL</includesBook>
    <includesBook>EPH</includesBook>
    <includesBook>PHP</includesBook>
    <includesBook>COL</includesBook>
    <includesBook>TH1</includesBook>
    <includesBook>TH2</includesBook>
    <includesBook>TI1</includesBook>
    <includesBook>TI2</includesBook>
    <includesBook>TIT</includesBook>
    <includesBook>PHM</includesBook>
    <!-- We'll include Hebrews here too by default -->
    <includesBook>HEB</includesBook>
  </BibleDivisionNames>


  <BibleBooknameLeaders standardLeader="1">
    <inputAbbreviation>I</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Première</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Premiere</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Prmre</inputAbbreviation>
    <inputAbbreviation>1st</inputAbbreviation>
    <inputAbbreviation>One</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="2">
    <inputAbbreviation>II</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Seconde</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Scnde</inputAbbreviation>
    <inputAbbreviation>2nd</inputAbbreviation>
    <inputAbbreviation>Two</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="3">
    <inputAbbreviation>III</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Troisième</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Troisieme</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Trsme</inputAbbreviation>
    <inputAbbreviation>3rd</inputAbbreviation>
    <inputAbbreviation>Three</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="4">
    <inputAbbreviation>IV</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Quatrième</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Quatrieme</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Qutrme</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Qtrme</inputAbbreviation>
    <inputAbbreviation>4th</inputAbbreviation>
    <inputAbbreviation>Four</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="5">
    <inputAbbreviation>V</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Cinquième</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Cinquieme</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Cnqme</inputAbbreviation>
    <inputAbbreviation>5th</inputAbbreviation>
    <inputAbbreviation>Five</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="6">
    <inputAbbreviation>VI</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Sixth</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Sxth</inputAbbreviation>
    <inputAbbreviation>6th</inputAbbreviation>
    <inputAbbreviation>Six</inputAbbreviation>
  </BibleBooknameLeaders>
  <BibleBooknameLeaders standardLeader="Saint">
    <inputAbbreviation>XXX-SPA-Snt</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-St</inputAbbreviation>
    <inputAbbreviation>XXX-SPA-Snt.</inputAbbreviation>
    <inputAbbreviation>St.</inputAbbreviation>
  </BibleBooknameLeaders>



  <BibleBookNames referenceAbbreviation="GEN">
    <defaultName>Génesis</defaultName>
    <defaultAbbreviation>Gen</defaultAbbreviation>
    <inputAbbreviation>Genese</inputAbbreviation>
    <inputAbbreviation>Gns</inputAbbreviation>
    <inputAbbreviation>1 Moses</inputAbbreviation>
    <inputAbbreviation>1 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EXO">
    <defaultName>Éxodo</defaultName>
    <defaultAbbreviation>Exo</defaultAbbreviation>
    <inputAbbreviation>Exde</inputAbbreviation>
    <inputAbbreviation>L'Exode</inputAbbreviation>
    <inputAbbreviation>L'Exde</inputAbbreviation>
    <inputAbbreviation>2 Moses</inputAbbreviation>
    <inputAbbreviation>2 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="LEV">
    <defaultName>Levítico</defaultName>
    <defaultAbbreviation>Lev</defaultAbbreviation>
    <inputAbbreviation>Levitique</inputAbbreviation>
    <inputAbbreviation>Lvtque</inputAbbreviation>
    <inputAbbreviation>3 Moses</inputAbbreviation>
    <inputAbbreviation>3 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="NUM">
    <defaultName>Números</defaultName>
    <defaultAbbreviation>Nom</defaultAbbreviation>
    <inputAbbreviation>Nmbrs</inputAbbreviation>
    <inputAbbreviation>4 Moses</inputAbbreviation>
    <inputAbbreviation>4 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="DEU">
    <defaultName>Deuteronomio</defaultName>
    <defaultAbbreviation>Deu</defaultAbbreviation>
    <inputAbbreviation>Deuteronome</inputAbbreviation>
    <inputAbbreviation>Dtrnme</inputAbbreviation>
    <inputAbbreviation>5 Moses</inputAbbreviation>
    <inputAbbreviation>5 Mss</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JOS">
    <defaultName>Josué</defaultName>
    <defaultAbbreviation>Jos</defaultAbbreviation>
    <inputAbbreviation>Josue</inputAbbreviation>
    <inputAbbreviation>Jsue</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JDG">
    <defaultName>Jueces</defaultName>
    <defaultAbbreviation>Jug</defaultAbbreviation>
    <inputAbbreviation>Jges</inputAbbreviation>
    <inputAbbreviation>Jgs</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="RUT">
    <defaultName>Rut</defaultName>
    <defaultAbbreviation>Rut</defaultAbbreviation>
    <inputAbbreviation>Rth</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="SA1">
    <defaultName>1 Samuel</defaultName>
    <defaultAbbreviation>1 Sam</defaultAbbreviation>
    <inputAbbreviation>1 Sml</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="SA2">
    <defaultName>2 Samuel</defaultName>
    <defaultAbbreviation>2 Sam</defaultAbbreviation>
    <inputAbbreviation>2 Sml</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="KI1">
    <defaultName>1 Reyes</defaultName>
    <defaultAbbreviation>1 Rs</defaultAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="KI2">
    <defaultName>2 Reyes</defaultName>
    <defaultAbbreviation>2 Rs</defaultAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CH1">
    <defaultName>1 Crónicas</defaultName>
    <defaultAbbreviation>1 Chr</defaultAbbreviation>
    <inputAbbreviation>1 Chrnqs</inputAbbreviation>
    <inputAbbreviation>1 Croniqs</inputAbbreviation>
    <inputAbbreviation>1 Crnq</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CH2">
    <defaultName>2 Crónicas</defaultName>
    <defaultAbbreviation>2 Chr</defaultAbbreviation>
    <inputAbbreviation>2 Chrnqs</inputAbbreviation>
    <inputAbbreviation>2 Croniqs</inputAbbreviation>
    <inputAbbreviation>2 Crnq</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EZR">
    <defaultName>Esdras</defaultName>
    <defaultAbbreviation>Esd</defaultAbbreviation>
    <inputAbbreviation>Esdrs</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="NEH">
    <defaultName>Nehemías</defaultName>
    <defaultAbbreviation>Neh</defaultAbbreviation>
    <inputAbbreviation>Nhmie</inputAbbreviation>
    <inputAbbreviation>Nehémie</inputAbbreviation>
    <inputAbbreviation>Néhemie</inputAbbreviation>
    <inputAbbreviation>Nehemie</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EST">
    <defaultName>Ester</defaultName>
    <defaultAbbreviation>Est</defaultAbbreviation>
    <inputAbbreviation>Esther</inputAbbreviation>
    <inputAbbreviation>Estr</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JOB">
    <defaultName>Job</defaultName>
    <defaultAbbreviation>Job</defaultAbbreviation>
    <inputAbbreviation>Jb</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PSA">
    <defaultName>Salmos</defaultName>
    <defaultAbbreviation>Psa</defaultAbbreviation>
    <inputAbbreviation>Psms</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PRO">
    <defaultName>Proverbios</defaultName>
    <defaultAbbreviation>Pro</defaultAbbreviation>
    <inputAbbreviation>Prvrbs</inputAbbreviation>
    <inputAbbreviation>Prvbs</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ECC">
    <defaultName>Eclesiastés</defaultName>
    <defaultAbbreviation>Ecc</defaultAbbreviation>
    <inputAbbreviation>Ecclesiaste</inputAbbreviation>
    <inputAbbreviation>L'Ecclésiaste</inputAbbreviation>
    <inputAbbreviation>L'Ecclesiaste</inputAbbreviation>
    <inputAbbreviation>Ecclst</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="SNG">
    <defaultName>Cantares</defaultName>
    <defaultAbbreviation>Cnt</defaultAbbreviation>
    <inputAbbreviation>Cantique des Cantiques</inputAbbreviation>
    <inputAbbreviation>Cnt de Slmn</inputAbbreviation>
    <inputAbbreviation>CdS</inputAbbreviation>
    <inputAbbreviation>CS</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ISA">
    <defaultName>Isaías</defaultName>
    <defaultAbbreviation>Ésa</defaultAbbreviation>
    <inputAbbreviation>Esaïe</inputAbbreviation>
    <inputAbbreviation>Esaie</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JER">
    <defaultName>Jeremías</defaultName>
    <defaultAbbreviation>Jér</defaultAbbreviation>
    <inputAbbreviation>Jeremie</inputAbbreviation>
    <inputAbbreviation>Jerémie</inputAbbreviation>
    <inputAbbreviation>Jéremie</inputAbbreviation>
    <inputAbbreviation>Jrm</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="LAM">
    <defaultName>Lamentaciones</defaultName>
    <defaultAbbreviation>Lam</defaultAbbreviation>
    <inputAbbreviation>Lmnts</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EZE">
    <defaultName>Ezequiel</defaultName>
    <defaultAbbreviation>Ézé</defaultAbbreviation>
    <inputAbbreviation>Ezechiel</inputAbbreviation>
    <inputAbbreviation>Ezéchiel</inputAbbreviation>
    <inputAbbreviation>Ézechiel</inputAbbreviation>
    <inputAbbreviation>Ézchl</inputAbbreviation>
    <inputAbbreviation>Ezchl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="DAN">
    <defaultName>Daniel</defaultName>
    <defaultAbbreviation>Dan</defaultAbbreviation>
    <inputAbbreviation>Dnl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HOS">
    <defaultName>Oseas</defaultName>
    <defaultAbbreviation>Osè</defaultAbbreviation>
    <inputAbbreviation>Osée</inputAbbreviation>
    <inputAbbreviation>Osee</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JOL">
    <defaultName>Joel</defaultName>
    <defaultAbbreviation>Joel</defaultAbbreviation>
    <inputAbbreviation>Jol</inputAbbreviation>
    <inputAbbreviation>Jl</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="AMO">
    <defaultName>Amós</defaultName>
    <defaultAbbreviation>Amos</defaultAbbreviation>
    <inputAbbreviation>Ams</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="OBA">
    <defaultName>Abdías</defaultName>
    <defaultAbbreviation>Abd</defaultAbbreviation>
    <inputAbbreviation>Abds</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JNA">
    <defaultName>Jonás</defaultName>
    <defaultAbbreviation>Jon</defaultAbbreviation>
    <inputAbbreviation>Jns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="MIC">
    <defaultName>Miqueas</defaultName>
    <defaultAbbreviation>Mic</defaultAbbreviation>
    <inputAbbreviation>Michee</inputAbbreviation>
    <inputAbbreviation>Mchée</inputAbbreviation>
    <inputAbbreviation>Mchee</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="NAH">
    <defaultName>Nahum</defaultName>
    <defaultAbbreviation>Nah</defaultAbbreviation>
    <inputAbbreviation>Nahm</inputAbbreviation>
    <inputAbbreviation>Nhum</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HAB">
    <defaultName>Habacuc</defaultName>
    <defaultAbbreviation>Hab</defaultAbbreviation>
    <inputAbbreviation>Habakuk</inputAbbreviation>
    <inputAbbreviation>Hbcc</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ZEP">
    <defaultName>Sofonías</defaultName>
    <defaultAbbreviation>Sop</defaultAbbreviation>
    <inputAbbreviation>Sphnie</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HAG">
    <defaultName>Hageo</defaultName>
    <defaultAbbreviation>Agg</defaultAbbreviation>
    <inputAbbreviation>Aggee</inputAbbreviation>
    <inputAbbreviation>Agée</inputAbbreviation>
    <inputAbbreviation>Agee</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ZEC">
    <defaultName>Zacarías</defaultName>
    <defaultAbbreviation>Zac</defaultAbbreviation>
    <inputAbbreviation>Zchrie</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="MAL">
    <defaultName>Malaquías</defaultName>
    <defaultAbbreviation>Mal</defaultAbbreviation>
    <inputAbbreviation>Mlchie</inputAbbreviation>
  </BibleBookNames>

  <BibleBookNames referenceAbbreviation="MAT">
    <defaultName>Mateo</defaultName>
    <defaultAbbreviation>Mat</defaultAbbreviation>
    <inputAbbreviation>Mtth</inputAbbreviation>
    <inputAbbreviation>Mth</inputAbbreviation>
    <inputAbbreviation>Saint Matthieu</inputAbbreviation>
    <inputAbbreviation>Saint Mtth</inputAbbreviation>
    <inputAbbreviation>Saint Mth</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="MRK">
    <defaultName>Marcos</defaultName>
    <defaultAbbreviation>Mrc</defaultAbbreviation>
    <inputAbbreviation>Mrk</inputAbbreviation>
    <inputAbbreviation>Mc</inputAbbreviation>
    <inputAbbreviation>Saint Marc</inputAbbreviation>
    <inputAbbreviation>Saint Mrc</inputAbbreviation>
    <inputAbbreviation>Saint Mc</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="LUK">
    <defaultName>Lucas</defaultName>
    <defaultAbbreviation>Luc</defaultAbbreviation>
    <inputAbbreviation>Lc</inputAbbreviation>
    <inputAbbreviation>Saint Luc</inputAbbreviation>
    <inputAbbreviation>Saint Lc</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="JHN">
    <defaultName>Juan</defaultName>
    <defaultAbbreviation>Jn</defaultAbbreviation>
    <inputAbbreviation>Saint Jean</inputAbbreviation>
    <inputAbbreviation>Saint Jn</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ACT">
    <defaultName>Hechos</defaultName>
    <defaultAbbreviation>Act</defaultAbbreviation>
    <inputAbbreviation>Acts</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="ROM">
    <defaultName>Romanos</defaultName>
    <defaultAbbreviation>Rom</defaultAbbreviation>
    <inputAbbreviation>Rmns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CO1">
    <defaultName>1 Corintios</defaultName>
    <defaultAbbreviation>1 Cor</defaultAbbreviation>
    <inputAbbreviation>1 Crnthns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="CO2">
    <defaultName>2 Corintios</defaultName>
    <defaultAbbreviation>2 Cor</defaultAbbreviation>
    <inputAbbreviation>2 Crnthns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="GAL">
    <defaultName>Gálatas</defaultName>
    <defaultAbbreviation>Gal</defaultAbbreviation>
    <inputAbbreviation>Glts</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="EPH">
    <defaultName>Efesios</defaultName>
    <defaultAbbreviation>Éph</defaultAbbreviation>
    <inputAbbreviation>Ephésiens</inputAbbreviation>
    <inputAbbreviation>Éphesiens</inputAbbreviation>
    <inputAbbreviation>Ephesiens</inputAbbreviation>
    <inputAbbreviation>Éphsns</inputAbbreviation>
    <inputAbbreviation>Ephsns</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PHP">
    <defaultName>Filipenses</defaultName>
    <defaultAbbreviation>Php</defaultAbbreviation>
    <inputAbbreviation>Phlppns</inputAbbreviation>
    <inputAbbreviation>Phlpns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>Phillipiens</inputAbbreviation>
    <inputAbbreviation>Philipiens</inputAbbreviation>
    <inputAbbreviation>Phillippiens</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="COL">
    <defaultName>Colosenses</defaultName>
    <defaultAbbreviation>Col</defaultAbbreviation>
    <inputAbbreviation>Clssns</inputAbbreviation>
    <inputAbbreviation>Clsns</inputAbbreviation>
    <inputAbbreviation>Cllssns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>Collosiens</inputAbbreviation>
    <inputAbbreviation>Collossiens</inputAbbreviation>
    <inputAbbreviation>Colosiens</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TH1">
    <defaultName>1 Tesalonicenses</defaultName>
    <defaultAbbreviation>1 Thess</defaultAbbreviation>
    <inputAbbreviation>1 Thsslncns</inputAbbreviation>
    <inputAbbreviation>1 Thslns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>1 Thesalloniciens</inputAbbreviation>
    <inputAbbreviation>1 Thessalloniciens</inputAbbreviation>
    <inputAbbreviation>1 Thesaloniciens</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TH2">
    <defaultName>2 Tesalonicenses</defaultName>
    <defaultAbbreviation>2 Thess</defaultAbbreviation>
    <inputAbbreviation>2 Thsslncns</inputAbbreviation>
    <inputAbbreviation>2 Thslns</inputAbbreviation>
    <!-- Include mispellings -->
    <inputAbbreviation>2 Thesalloniciens</inputAbbreviation>
    <inputAbbreviation>2 Thessalloniciens</inputAbbreviation>
    <inputAbbreviation>2 Thesaloniciens</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TI1">
    <defaultName>1 Timoteo</defaultName>
    <defaultAbbreviation>1 Tim</defaultAbbreviation>
    <inputAbbreviation>1 Tmth</inputAbbreviation>
    <inputAbbreviation>1 Timothee</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TI2">
    <defaultName>2 Timoteo</defaultName>
    <defaultAbbreviation>2 Tim</defaultAbbreviation>
    <inputAbbreviation>2 Tmth</inputAbbreviation>
    <inputAbbreviation>2 Timothee</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="TIT">
    <defaultName>Tito</defaultName>
    <defaultAbbreviation>Tit</defaultAbbreviation>
    <inputAbbreviation>Tte</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="PHM">
    <defaultName>Filemón</defaultName>
    <defaultAbbreviation>Phm</defaultAbbreviation>
    <inputAbbreviation>Phlmn</inputAbbreviation>
    <inputAbbreviation>Philemon</inputAbbreviation>
  </BibleBookNames>
  <BibleBookNames referenceAbbreviation="HEB">
    <defaultName>Hebreos</defaultName>
    <defaultAbbreviation>Heb</defaultAbbreviation>
    <inputAbbreviation>Hbrx</inputAbbreviation>