<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of available Bible organizational systems including
    A unique English organizational system name (as a comment only)
        (This table should be language agnostic although English is used as a meta-language.)
    A unique reference abbreviation
    The type:   original    e.g., Hebrew/Greek scriptures
                translation e.g., 1611grep  King James Version (KJV)
                revision    e.g., 1769 King James Version
                edition     e.g., NIV Women's Study Bible (An edition uses a translation)
    The definitive names with the language specified as an ISO 639-3 code in an attribute.
    A versificationSystem name field which directs to that versification system.
    A punctuationSystem name field which directs to the punctuation system.
        None and Unknown are also valid entries for the system name fields.

The historical data encoded in this document is approximate only.
It's impossible to accurately list all of the adjustments and revisions of texts that were made,
especially since the text of some early versions is no longer available.

The data is preceded by a header of the same format as an OSIS header.

Note that most of the data is supplied as XML elements, not attributes.

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied ReadMe.txt for more details.
-->

<!DOCTYPE BibleOrganisationalSystems [
    <!ELEMENT BibleOrganisationalSystems (header,BibleOrganisationalSystem+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier*,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|cre|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleOrganisationalSystem (referenceAbbreviation,languageCode,name+,derivedFrom*,translator*,completionDate*,publicationDate*,
                        versificationSystem*,punctuationSystem*,bookOrderSystem*,booksNamesSystem*,usesText*,url*)>
            <!ATTLIST BibleOrganisationalSystem type CDATA #REQUIRED>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT languageCode (#PCDATA)>
            <!ELEMENT name (#PCDATA)>
            <!ELEMENT translator (#PCDATA)>
            <!ELEMENT derivedFrom (#PCDATA)>
            <!ELEMENT publicationDate (#PCDATA)>
            <!ELEMENT versificationSystem (#PCDATA)>
            <!ELEMENT punctuationSystem (#PCDATA)>
            <!ELEMENT bookOrderSystem (#PCDATA)>
            <!ELEMENT booksNamesSystem (#PCDATA)>
            <!ELEMENT usesText (#PCDATA)>
            <!ELEMENT url (#PCDATA)>
]>

<BibleOrganisationalSystems>

  <header>
    <work>
      <version>0.29</version>
      <date>2019-11-10</date>
      <title>Bible organizational systems list</title>
      <contributor role="com">Robert Hunt</contributor>
      <rights>Public Domain</rights>
      <identifier type="URL">http://en.wikipedia.org/wiki/English_translations_of_the_Bible</identifier>
      <identifier type="URL">http://en.wikipedia.org/wiki/List_of_English_Bible_translations</identifier>
      <identifier type="URL">http://www.biblicaltraining.org/history-english-bible/daniel-wallace/foundations</identifier>
      <identifier type="URL">http://www.lockman.org/nasb/nasbprin.php</identifier>
</work>
  </header>


<!-- Original Bible texts -->
  <BibleOrganisationalSystem type="original">
    <referenceAbbreviation>HEB</referenceAbbreviation>
    <languageCode>hbo</languageCode>
    <name>Hebrew Scriptures</name>
    <versificationSystem>Hebrew</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Hebrew</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL</includesBooks>
    <url>http://en.wikipedia.org/wiki/Hebrew_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="original">
    <referenceAbbreviation>NTG</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Greek Scriptures</name>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Unknown</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Greek_New_Testament</url>
  </BibleOrganisationalSystem>


<!-- Translations from originals, and -->
<!-- Revisions of earlier translations -->
  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>LXX</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Septuagint</name>
    <name>LXX</name>
    <publicationDate>300 BC</publicationDate>
    <derivedFrom>HEB</derivedFrom>
    <versificationSystem>Septuagint</versificationSystem>
    <punctuationSystem>None</punctuationSystem>
    <bookOrderSystem>Septuagint</bookOrderSystem>
    <booksNamesSystem>None</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL</includesBooks>
    <url>http://en.wikipedia.org/wiki/Septuagint</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>VUL</referenceAbbreviation>
    <languageCode>lat</languageCode>
    <name>Vulgate</name>
    <name>Versio Vulgata</name>
    <translator>Jerome</translator>
    <translator>others</translator>
    <comment>Commissioned by Pope Damasus in 382</comment>
    <derivedFrom>HEB</derivedFrom>
    <derivedFrom>LXX</derivedFrom>
    <publicationDate>405</publicationDate>
    <versificationSystem>Vulgate</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    JDT TOB WIS SIR MAC
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/St_Jerome</url>
    <url>http://en.wikipedia.org/wiki/Vulgate</url>
    <url>http://en.wikipedia.org/wiki/Pope_Damasus_I</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>BJ</referenceAbbreviation>
    <languageCode>ang</languageCode>
    <name>Unknown</name>
    <translator>The Venerable Bede</translator>
    <publicationDate>735</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>JHN</includesBooks>
    <url>http://en.wikipedia.org/wiki/Venerable_Bede</url>
    <url>http://en.wikipedia.org/wiki/List_of_works_by_Bede</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>AGP</referenceAbbreviation>
    <languageCode>ang</languageCode>
    <name>Unknown</name>
    <translator>King Alfred the Great</translator>
    <derivedFrom>VUL</derivedFrom>
    <publicationDate>900</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU</includesBooks>
    <url>http://en.wikipedia.org/wiki/Alfred_the_Great</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>WYC-1382</referenceAbbreviation>
    <languageCode>enm</languageCode>
    <name>Wycliffe Bible</name>
    <translator>John Wycliffe</translator>
    <translator>others</translator>
    <derivedFrom>VUL</derivedFrom>
    <publicationDate>1382</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/John_Wycliffe</url>
    <url>http://en.wikipedia.org/wiki/Wycliffe's_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="revision">
    <referenceAbbreviation>WYC-1395</referenceAbbreviation>
    <languageCode>enm</languageCode>
    <name>Wycliffe Bible</name>
    <translator>John Purvey</translator>
    <derivedFrom>WYC-1382</derivedFrom>
    <publicationDate>1395</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/John_Wycliffe</url>
    <url>http://en.wikipedia.org/wiki/John_Purvey</url>
    <url>http://en.wikipedia.org/wiki/Wycliffe's_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>MENTEL</referenceAbbreviation>
    <languageCode>deu</languageCode>
    <name>Mentel Bible</name>
    <translator>Johannes_Mentelin</translator>
    <publicationDate>1466</publicationDate>
    <comment>Printed at Strassburg</comment>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>Unknown</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>deu_traditional</booksNamesSystem>
    <url>http://en.wikipedia.org/wiki/Johannes_Mentelin</url>
    <url>http://en.wikipedia.org/wiki/German_Bible_translations</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>EL-1</referenceAbbreviation>
    <languageCode>lat</languageCode>
    <name>Erasmus' Latin New Testament -- 1st edition</name>
    <translator>Desiderius Erasmus</translator>
    <derivedFrom>VUL</derivedFrom>
    <publicationDate>1516</publicationDate>
    <comment>Produced in a rush to be first</comment>
    <url>http://en.wikipedia.org/wiki/Erasmus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>ENTG-1</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Erasmus' Greek New Testament -- 1st edition</name>
    <translator>Desiderius Erasmus</translator>
    <publicationDate>1 March 1516</publicationDate>
    <comment>Produced in a rush to be first</comment>
    <comment>The final six verses of Greek Revelation were back-translated from the Latin</comment>
    <comment>Called the most poorly edited book in the world</comment>
    <usesText>EL-1</usesText>
    <usesText>NTG</usesText>
    <comment>Latin/Greek diglot</comment>
    <url>http://en.wikipedia.org/wiki/Erasmus</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>ENTG-2</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Erasmus' Greek New Testament -- 2nd edition</name>
    <translator>Desiderius Erasmus</translator>
    <publicationDate>1519</publicationDate>
    <usesText>EL</usesText>
    <usesText>NTG</usesText>
    <comment>Latin/Greek diglot</comment>
    <url>http://en.wikipedia.org/wiki/Erasmus</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>TYN-NT-1526</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Tyndale New Testament</name>
    <translator>William Tyndale</translator>
    <derivedFrom>EGNT</derivedFrom>
    <completionDate>1525</completionDate>
    <publicationDate>1526</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/William_Tyndale</url>
    <url>http://en.wikipedia.org/wiki/Tyndale_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>TYN-1526</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Tyndale Bible</name>
    <translator>William Tyndale</translator>
    <derivedFrom>NTG</derivedFrom>
    <completionDate>1525</completionDate>
    <publicationDate>1526</publicationDate>
    <comment>Used italics for words not in the original</comment>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/William_Tyndale</url>
    <url>http://en.wikipedia.org/wiki/Tyndale_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>LUT</referenceAbbreviation>
    <languageCode>deu</languageCode>
    <name>Luther Bible</name>
    <translator>Martin Luther</translator>
    <derivedFrom>NTG</derivedFrom>
    <publicationDate>1534</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    TOB JDT ESG WIS SIR BAR LJE PAZ SUS BEL MA1 MA2 GES LES MAN
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Martin_Luther</url>
    <url>http://en.wikipedia.org/wiki/Luther_Bible</url>
    </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="revision">
    <referenceAbbreviation>TYN-NT-2</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Tyndale New Testament -- 2nd edition</name>
    <derivedFrom>TYN-NT-1526</derivedFrom>
    <publicationDate>1534</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Tyndale_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>ENTG-3</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Erasmus' Greek New Testament -- 3rd edition</name>
    <translator>Desiderius Erasmus</translator>
    <publicationDate>1522</publicationDate>
    <usesText>EL</usesText>
    <usesText>NTG</usesText>
    <comment>Latin/Greek diglot</comment>
    <url>http://en.wikipedia.org/wiki/Erasmus</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>ENTG-4</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <translator>Desiderius Erasmus</translator>
    <name>Erasmus' Greek New Testament -- nth edition</name>
    <publicationDate>1532</publicationDate>
    <usesText>EL</usesText>
    <usesText>NTG</usesText>
    <comment>Latin/Greek diglot</comment>
    <url>http://en.wikipedia.org/wiki/Erasmus</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>ENTG-5</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <translator>Desiderius Erasmus</translator>
    <name>Erasmus' Greek New Testament -- nth edition</name>
    <publicationDate>1532</publicationDate>
    <usesText>EL</usesText>
    <usesText>NTG</usesText>
    <usesText>ENTG</usesText>
    <comment>Latin/Greek diglot</comment>
    <url>http://en.wikipedia.org/wiki/Erasmus</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>CB</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Coverdale Bible</name>
    <comment>Title was "Biblia, The Bible, that is to say, the Holy Scriptures of Old and New Testament"</comment>
    <translator>Myles Coverdale</translator>
    <derivedFrom>LUT</derivedFrom>
    <derivedFrom>VUL</derivedFrom>
    <derivedFrom>TYN</derivedFrom>
    <comment>Also derived from: the Latin version of Paginus, the Zurich version</comment>
    <publicationDate>October 4, 1535</publicationDate>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    TOB JDT ESG WIS SIR BAR LJE PAZ SUS BEL MA1 MA2 GES LES MAN
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Myles_Coverdale</url>
    <url>http://en.wikipedia.org/wiki/Coverdale_Bible</url>
    <url>http://creation.com/coverdale</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="revision">
    <referenceAbbreviation>TYN-NT-3</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Tyndale New Testament -- 3rd edition</name>
    <derivedFrom>TYN-NT-2</derivedFrom>
    <publicationDate>1536</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Tyndale_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="revision">
    <referenceAbbreviation>TYN-NT-4</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Tyndale New Testament -- 4th edition</name>
    <derivedFrom>TYN-NT-3</derivedFrom>
    <publicationDate>???</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Tyndale_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="revision">
    <referenceAbbreviation>TYN-NT-5</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Tyndale New Testament -- 5th edition</name>
    <derivedFrom>TYN-NT-4</derivedFrom>
    <publicationDate>???</publicationDate>
    <versificationSystem>KJV</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Tyndale_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>MB</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Matthew's Bible</name>
    <comment>Known as "The Wife beater's Bible"</comment>
    <translator>John Rogers</translator>
    <comment>Pen name Thomas Matthew</comment>
    <derivedFrom>CB</derivedFrom>
    <derivedFrom>TYN</derivedFrom>
    <publicationDate>1537</publicationDate>
    <comment>Large folio size with extensive marginal notes</comment>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    TOB JDT ESG WIS SIR BAR LJE PAZ SUS BEL MA1 MA3 GES LES MAN
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/John_Rogers_(Bible_editor_and_martyr)</url>
    <url>http://en.wikipedia.org/wiki/Matthew's_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="translation">
    <referenceAbbreviation>GrtB</referenceAbbreviation>
    <languageCode>eng</languageCode>
    <name>Great Bible</name>
    <name>Cromwell Bible</name>
    <name>Whitchurch's Bible</name>
    <name>The Chained Bible</name>
    <translator>Myles Coverdale</translator>
    <derivedFrom>MB</derivedFrom>
    <publicationDate>April 1539</publicationDate>
    <comment>Extra large folio version</comment>
    <versificationSystem>None</versificationSystem>
    <punctuationSystem>English</punctuationSystem>
    <bookOrderSystem>EuropeanBible</bookOrderSystem>
    <booksNamesSystem>eng_traditional</booksNamesSystem>
    <includesBooks>GEN EXO LEV NUM DEU JOS JDG RUT SA1 SA2 KI1 KI2 CH1 CH2 EZR NEH EST JOB PSA PRO ECC SNG ISA JER LAM EZE DAN HOS JOL AMO OBA JNA MIC NAH HAB ZEP HAG ZEC MAL
                    TOB JDT ESG WIS SIR BAR LJE PAZ SUS BEL MA1 MA2 GES LES MAN
                    MAT MRK LUK JHN ACT ROM CO1 CO2 GAL EPH PHP COL TH1 TH2 TI1 TI2 TIT PHM HEB JAM PE1 PE2 JN1 JN2 JN3 JDE REV</includesBooks>
    <url>http://en.wikipedia.org/wiki/Myles_Coverdale</url>
    <url>http://en.wikipedia.org/wiki/Great_Bible</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>SNTG-1</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Stephanus' Greek New Testament -- 1st edition</name>
    <translator>Robert Estienne</translator>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Robert_Estienne</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>SNTG-2</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <translator>Robert Estienne</translator>
    <derivedFrom>SNTG-1</derivedFrom>
    <name>Stephanus' Greek New Testament -- 2nd edition</name>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Robert_Estienne</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>SNTG-3</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Stephanus' Greek New Testament -- 3rd edition</name>
    <translator>Robert Estienne</translator>
    <derivedFrom>SNTG-2</derivedFrom>
    <derivedFrom>ENTG-3</derivedFrom>
    <publicationDate>1550</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Robert_Estienne</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>SNTG-4</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <translator>Robert Estienne</translator>
    <derivedFrom>SNTG-3</derivedFrom>
    <name>Stephanus' Greek New Testament -- 4th edition</name>
    <publicationDate>1551</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Robert_Estienne</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-1</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 1st edition</name>
    <derivedFrom>SNTG-4</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-2</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 2nd edition</name>
    <derivedFrom>BNTG-1</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-3</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 3rd edition</name>
    <derivedFrom>BNTG-2</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-4</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 4th edition</name>
    <derivedFrom>BNTG-3</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-5</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 5th edition</name>
    <derivedFrom>BNTG-4</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-6</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 6th edition</name>
    <derivedFrom>BNTG-5</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-7</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 7th edition</name>
    <derivedFrom>BNTG-6</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>
  </BibleOrganisationalSystem>

  <BibleOrganisationalSystem type="edition">
    <referenceAbbreviation>BNTG-8</referenceAbbreviation>
    <languageCode>grc</languageCode>
    <name>Theodore Beza's Greek New Testament -- 8th edition</name>
    <derivedFrom>BNTG-7</derivedFrom>
    <publicationDate>???</publicationDate>
    <usesText>NTG</usesText>
    <url>http://en.wikipedia.org/wiki/Theodore_Beza</url>
    <url>http://en.wikipedia.org/wiki/Textus_Receptus</url>